### ISSUE TITLE
radium ??? CSS in JS

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#103]
# radium ??? CSS in JS

https://github.com/FormidableLabs/radium

https://alexcurtis.github.io/react-treebeard/

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/29713625-1bb0793e-89d2-11e7-8b33-e0b1196d45f2.png)

> bug


```css
#treebox ul {
    list-style: none;
    background-color: rgb(33, 37, 43);
    /* background-color: rgba(33, 37, 43, 0.7); */
    margin: 0px;
    padding: 0px;
    color: rgb(157, 165, 171);
    font-family: "lucida grande", tahoma, verdana, arial, sans-serif;
    font-size: 14px;
    width: 300px;
    overflow-x: hidden;
    /* min-width: 260px; */
    /* min-width: 200px; */
}

```

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions
