### ISSUE TITLE
 CSS flex  & `display: 'flex'`

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#108]
#  CSS flex 

> `display: 'flex'`

**Comment by xgqfrms-gildata** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

**Comment by xgqfrms-gildata** [comment]
# calc()


https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by xgqfrms-gildata** [comment]
# media query

https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by xgqfrms-gildata** [comment]
# layout

https://css-tricks.com/

http://learnlayout.com/

**Comment by xgqfrms-gildata** [comment]
https://www.cnblogs.com/pigtail/archive/2012/11/25/2787508.html

**Comment by xgqfrms-gildata** [comment]
# scroll-bar

https://stackoverflow.com/questions/9251354/css-customized-scroll-bar-in-div

**Comment by xgqfrms-gildata** [comment]
https://github.com/gildata/RAIO/issues/84

https://github.com/gildata/RAIO/issues/42

https://css-tricks.com/almanac/properties/o/overflow/

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/29768070-6dd2126c-8c17-11e7-875e-5f4cde9f9cbb.png)


```css

.tbs-width {
    /* max-width: calc(100% - 300px); */
    /* max-width: 1000px; */
    /* min-width: 1000px; */
    /* margin-left: 300px; */
    width: 100%;
    height: 100%;
    overflow: hidden;
    box-sizing: border-box;
    /* float: left; */
}

/* 

.tbs-width {
    max-width: calc(100% - 300px);
    margin-left: 300px;
    width: 100%;
    height: 100%;
    overflow: hidden;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    float: left;
}

*/

```
