### ISSUE TITLE
CSS : cursor & :nth-of-type() & :nth-child

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gildata/RAIO#166]
# cursor & :nth-of-type() & :nth-child

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child

https://codepen.io/anon/pen/bopvJp

> :nth-of-type() & :nth-child

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

```css

.title-color {
    margin-left: 10px;
    font-size: 18px;
    color: #108ee9;
    cursor: pointer;
}



p.title-color:nth-of-type(3) {
    /* margin-left: 10px;
    font-size: 18px;
    color: #108ee9; */
    cursor: not-allowed;
}

```

**Comment by xgqfrms-GitHub** [comment]
# url & cursor

```css

/* url & cursor */

.cursorAll{
    cursor: url(one.svg), url(two.svg) 5 5, progress;
}


```
