### ISSUE TITLE
HTML5 data Attributes & React JSX

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#174]
# HTML5 data Attributes & React JSX

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

```html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>data-*</title>
</head>
<body>
    <article
        id="electriccars"
        data-columns="3"
        data-index-number="12314"
        data-parent="cars">
        ...somthings
    </article>
</body>
</html>

```

1. JavaScript access

> dataset

```js
    // getAttribute() & dataset
    let article = document.getElementById('electriccars');
    article.dataset.columns // "3"
    article.dataset.indexNumber // "12314"
    article.dataset.parent // "cars"
```

2. CSS access

>

```css

    /*  CSS attr() function */
    article::before {
        content: attr(data-parent);
    }
    /* CSS attribute selectors */
    article[data-columns='3'] {
        width: 400px;
    }
    article[data-columns='4'] {
        width: 600px;
    }

```

https://www.sitepoint.com/use-html5-data-attributes/

1. JavaScript Parsing #1: getAttribute and setAttribute
2. JavaScript Parsing #2: jQuery data() method
3. JavaScript Parsing #3: the dataset API

![image](https://user-images.githubusercontent.com/29531779/30949962-260ea6aa-a44c-11e7-8169-6cb88e2dbbdf.png)

https://facebook.github.io/react/docs/dom-elements.html

https://stackoverflow.com/questions/27285856/how-do-i-dynamically-set-html5-data-attributes-using-react
https://facebook.github.io/react/docs/jsx-in-depth.html#javascript-expressions
https://stackoverflow.com/questions/41105316/how-to-get-the-value-of-html5-data-attribute-in-react-js

## HTML5 Drag and Drop

https://www.sitepoint.com/html5-native-drag-and-drop-api/
https://www.w3schools.com/html/html5_draganddrop.asp
