### ISSUE TITLE
 HTML5 Drag and Drop

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gildata/RAIO#178]
# HTML5 Drag and Drop

https://github.com/gildata/RAIO-new/issues/3

**Comment by xgqfrms-GitHub** [comment]
# search button & emoji & data-emoji="uid_emoji🚧"

```css

.SidebarNav_search button {
    position: absolute;
    background: transparent;
    top: 0;
    left: 1em;
}


#sp🚧 .l-pa0 {
    padding: 0;
}


#sp🚧 .l-b-n {
    border: none;
}

#sp🚧 .l-h-100 {
    height: 100%;
}

#sp🚧 .f-c-grey-500 {
    color: #3a3a3a;
}

```


![image](https://user-images.githubusercontent.com/18028768/31052478-6b5718aa-a6b8-11e7-92e7-91bb925eaf03.png)

# node.js

https://nodeschool.io/zh-cn/

**Comment by xgqfrms-GitHub** [comment]
https://translate.google.com/?source=gtx_c#auto/zh-CN/Kudos

> Kudos === 荣誉

**Comment by xgqfrms-GitHub** [comment]
```js

(function() {
	try {
		var i, environmentVars = '', e = document.createEvent('Events');

		e.initEvent('wappalyzerEvent', true, false);

		for ( i in window ) {
			environmentVars += i + ' ';
		}

		document.getElementById('wappalyzerData').appendChild(document.createComment(environmentVars));
		document.getElementById('wappalyzerData').dispatchEvent(e);
	} catch(e) {
		// Fail quietly
 	}
}());


```

https://jakearchibald.com/

http://lanyrd.com/profile/jaffathecake/
https://wicg.github.io/background-fetch/

https://github.com/jakearchibald/simple-serviceworker-tutorial

https://github.com/WICG/background-fetch/blob/gh-pages/index.html

```js


document.body.addEventListener("click", function(e) {
    var queryAll = function(sel) { return [].slice.call(document.querySelectorAll(sel)); }
    // Find the dfn element or panel, if any, that was clicked on.
    var el = e.target;
    var target;
    var hitALink = false;
    while(el.parentElement) {
        if(el.tagName == "A") {
            // Clicking on a link in a <dfn> shouldn't summon the panel
            hitALink = true;
        }
        if(el.classList.contains("dfn-paneled")) {
            target = "dfn";
            break;
        }
        if(el.classList.contains("dfn-panel")) {
            target = "dfn-panel";
            break;
        }
        el = el.parentElement;
    }
    if(target != "dfn-panel") {
        // Turn off any currently "on" or "activated" panels.
        queryAll(".dfn-panel.on, .dfn-panel.activated").forEach(function(el){
            el.classList.remove("on");
            el.classList.remove("activated");
        });
    }
    if(target == "dfn" && !hitALink) {
        // open the panel
        var dfnPanel = document.querySelector(".dfn-panel[data-for='" + el.id + "']");
        if(dfnPanel) {
            console.log(dfnPanel);
            dfnPanel.classList.add("on");
            var rect = el.getBoundingClientRect();
            dfnPanel.style.left = window.scrollX + rect.right + 5 + "px";
            dfnPanel.style.top = window.scrollY + rect.top + "px";
            var panelRect = dfnPanel.getBoundingClientRect();
            var panelWidth = panelRect.right - panelRect.left;
            if(panelRect.right > document.body.scrollWidth && (rect.left - (panelWidth + 5)) > 0) {
                // Reposition, because the panel is overflowing
                dfnPanel.style.left = window.scrollX + rect.left - (panelWidth + 5) + "px";
            }
        } else {
            console.log("Couldn't find .dfn-panel[data-for='" + el.id + "']");
        }
    } else if(target == "dfn-panel") {
        // Switch it to "activated" state, which pins it.
        el.classList.add("activated");
        el.style.left = null;
        el.style.top = null;
    }
});

```

https://wicg.github.io/background-fetch/

**Comment by xgqfrms-GitHub** [comment]
#  ES6  & IIFE

```js

// ES6  & IIFE
(() => {
   try {
       console.log(`😃 🙌 🎉 Hooray!`);
       // https://emojipedia.org/search/?q=tada
   } catch(error) {
       // Fail quietly
       console.log(`😭 😢 😂 😿 😞 💩 Holy Shit!`);
       // https://emojipedia.org/pile-of-poo/
       // https://emojipedia.org/search/?q=cry
       // throw new Error(`meesage`, error);
   }
})();
// 😃 🙌 🎉 Hooray!


```

**Comment by xgqfrms-GitHub** [comment]
```html

<section>
        <div>
            <a href="https://github.com/xgqfrms/cdn/new/gh-pages/es6-modules/chrome">es6-modules/chrome</a>
        </div>
        <div id="uid_es6_modules" data-uid="uid-es6-modules">
            <!-- placeholder -->
        </div>
         <div id="uid_es6_iife" data-uid-iife="uid-es6-iife">
            <!-- placeholder -->
        </div>
        <script>
            let div = document.querySelector(`#uid_es6_modules`);
            // div.dataset[`uid-es6-modules`];
            let uid = div.dataset.uid;
            // let uid = div.dataset[`uid`];
            // "uid-es6-modules"
            // let div = document.querySelector(`#uid_es6_iife`);
            // let iife = div.dataset[`uidIife`];
            // let iife = div.dataset.uidIife;
            // ES6  & IIFE
            (() => {
               try {
                   console.log(`😃 🙌 🎉 Hooray!`);
                   // https://emojipedia.org/search/?q=tada
                   div.insertAdjacentHTML(`beforeend`, '<div id="two">`😃 🙌 🎉 Hooray!`</div>');
               } catch(error) {
                   // Fail quietly
                   console.log(`😭 😢 😂 😿 😞 💩 Holy Shit!`);
                   // https://emojipedia.org/pile-of-poo/
                   // https://emojipedia.org/search/?q=cry
                   // throw new Error(`meesage`, error);
               }
            })();
            // 😃 🙌 🎉 Hooray!
        </script>
    </section>

```

**Comment by xgqfrms-GitHub** [comment]
# code highlight
```css
@import 'buttons';

.site-header {
  background: #2D2D2D;
  overflow: hidden;

  & > .inner {
    padding-top: 75px;
    padding-left: 0;
    @media screen and (min-width: $mobile-boundry) {
      padding-top: 135px;
    }
  }

  & a:link,
  & a:visited {
    color: #fff;
  }
  & a:hover,
  & a:active {
    color: #fff;
    text-decoration: underline;
  }

  & .title,
  & .who {
    background: #009D81;
    line-height: 1;
    font-family: "PT Serif", georgia, serif;
    display: inline-block;
    font-size: 1.05rem;
    padding: 10px 45px 10px 20px;

    @media screen and (min-width: $mobile-boundry) {
      padding: 10px 97px 10px 32px;
    }
    @media screen and (min-width: $full-width) {
      border-radius: 7px 7px 0 0;
    }
  }

  & .who {
    float: right;
    padding: 10px 0;
    background: none;
    margin-right: 0;

    @media screen and (min-width: $mobile-boundry) {
      margin-right: -32px;
    }

    @media screen and (min-width: $side-introduction-width) {
      position: absolute;
      right: 25%;
      padding-right: 90px;

      .js & {
        display: none;
      }
    }
  }
}

// headings
  %h-1 {
    background: #FF8400;
    color: #FFF;
    margin: 0;
    font-family: "PT Serif", georgia, serif;
    font-size: 2.5rem;
    font-weight: normal;
    line-height: 1.1;
    margin-left: -20px;
    padding: 7px 20px 13px 20px;

    @media screen and (min-width: $mobile-boundry) {
      font-size: 3.4rem;
      padding: 10px 36px 17px 62px;
      margin-left: -65px;
      margin-right: -32px;
    }

    @media screen and (min-width: $full-width) {
      border-radius: 32px 0 0 32px;
    }
  }
  .h-1 { @extend %h-1; }

  %h-2 {
    background: #009D81;
    color: #FFF;
    margin: 35px 0 0;
    font-family: "PT Serif", georgia, serif;
    font-size: 1.6rem;
    font-weight: normal;
    line-height: 1;
    padding: 7px 20px 10px 20px;
    margin-left: -20px;

    @media screen and (min-width: $mobile-boundry) {
      font-size: 1.9rem;
      padding: 10px 35px 13px 62px;
      margin-right: -32px;
      margin-left: -65px;
    }

    @media screen and (min-width: $full-width) {
      border-radius: 32px 0 0 32px;
    }
  }
  .h-2 { @extend %h-2; }

  %h-3 {
    margin: 27px 0 0;
    line-height: 1;
    font-family: sans-serif;
    font-weight: bold;
    font-size: 1rem;
    border-left: 14px solid #FF8400;
    padding-left: 8px;

    @media screen and (min-width: $mobile-boundry) {
      font-size: 1.2rem;
      border-left: 19px solid #FF8400;
      padding-left: 12px;
    }
  }
  .h-3 { @extend %h-3; }

  %h-4 {
    font-weight: normal;
    font-size: 0.9rem;
    border-bottom: 1px dotted #CCC;
    padding-bottom: 3px;
    margin: 1.4em 0 0;
    line-height: 1;
  }
  .h-4 { @extend %h-4; }

// content styles
  .article-date {
    font-size: 0.8rem;
    display: block;
    background: #FFE454;
    color: #000;
    padding: 6px 20px 5px 20px;
    margin: 0 0 0 -20px;

    @media screen and (min-width: $mobile-boundry) {
      padding: 6px 10px 5px 32px;
      margin-left: -32px;
      margin-right: -32px;
    }
  }

// article content
  .article-content {
    & h1 {
      @extend %h-1;
    }
    & h2 {
      @extend %h-2;
    }
    & h3 {
      @extend %h-3;
    }
    & code {
      font-family: Inconsolata, courier, monospace;
      background: #EEE;
      padding: 3px 3px;
      margin: 0 2px;
      outline: 1px solid #E2E2E2;
      line-height: 1;
      white-space: normal;
      display: inline-block;
    }
  }

// figures
  .full-figure {
    margin: 1em -20px;
    overflow: hidden;
    background: #eee;

    @media screen and (min-width: $mobile-boundry) {
      margin-left: 0;
      margin-right: 0;
    }

    &.checked {
      background: url('imgs/check.png');
    }

    &.blueprint {
      background: url('imgs/graph-tile.png'), radial-gradient(circle farthest-corner, #08d, #002b46) center;
      background-size: 12%, cover;
    }

    & img,
    & iframe,
    & video,
    & object {
      display: block;
      margin: 0 auto;
    }

    & .video {
      position: relative;
      padding-top: 56.25%;

      & iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
    }

    & > figcaption {
      font-size: 0.8rem;
      line-height: 1.4;
      background: #FFE454;
      color: #000;
      padding: 6px 20px;

      @media screen and (min-width: $mobile-boundry) {
        padding: 6px 10px;
      }
    }
  }

// 'who' sidebar
  .side {
    font-size: 0.85rem;
    font-weight: normal;

    & > section > h1 {
      @extend %h-4;
    }

    & .icon-list {
      margin: 1em 0;
      display: flex;
      flex-flow: row wrap;

      & > li {
        flex: 0 0 50%;
      }
    }
  }
  .my-big-face {
    margin-top: 10px;

    & h1 {
      position: relative;
      margin: 0;
      // the values in percentage are imgHeight / imgWidth
      padding: percentage(328 / 430) 0 0 0;
      outline: 10px solid #fff;
      background: #fff;
    }
    & img {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
  }

// script
  .codehilite {
    background: #2D2D2D;
    color: #E4E4E4;
    margin: 1em -20px;
    padding: 16px 20px;
    line-height: 1.4;
    font-size: 1rem;
    overflow: auto;

    @media screen and (min-width: $mobile-boundry) {
      margin-left: -32px;
      margin-right: 0;
      padding-left: 32px;
      padding-right: 0;
      font-size: 1.1rem;
    }

    & pre {
      font-family: Inconsolata, courier, monospace;
      margin: 0;
      // add some padding on the right-hand side when scrolling
      display: inline-block;
      padding-right: 16px;
    }
  }

  .codehilite .hll { background-color: #ffffcc }
  .codehilite .c { color: #f48c5f} /* Comment */
  .codehilite .err { color: #E4E4E4} /* Error */
  .codehilite .g { color: #E4E4E4} /* Generic */
  .codehilite .k { color: #b294bb} /* Keyword */
  .codehilite .l { color: #E4E4E4} /* Literal */
  .codehilite .n { color: #E4E4E4} /* Name */
  .codehilite .o { color: #6cc0b7} /* Operator */
  .codehilite .x { color: #E4E4E4} /* Other */
  .codehilite .p { color: #E4E4E4} /* Punctuation */
  .codehilite .cm { color: #f48c5f} /* Comment.Multiline */
  .codehilite .cp { color: #fcaf3e} /* Comment.Preproc */
  .codehilite .c1 { color: #f48c5f} /* Comment.Single */
  .codehilite .cs { color: #f48c5f} /* Comment.Special */
  .codehilite .gd { color: #2e3436; background-color: #0e1416 } /* Generic.Deleted */
  .codehilite .ge { color: #E4E4E4} /* Generic.Emph */
  .codehilite .gr { color: #eeeeec; background-color: #cc0000 } /* Generic.Error */
  .codehilite .gh { color: #fcaf3e} /* Generic.Heading */
  .codehilite .gi { color: #E4E4E4; background-color: #1f2b2d } /* Generic.Inserted */
  .codehilite .go { color: #2c3032; background-color: #2c3032 } /* Generic.Output */
  .codehilite .gp { color: #E4E4E4} /* Generic.Prompt */
  .codehilite .gs { color: #E4E4E4} /* Generic.Strong */
  .codehilite .gu { color: #fcaf3e} /* Generic.Subheading */
  .codehilite .gt { color: #E4E4E4} /* Generic.Traceback */
  .codehilite .kc { color: #b294bb} /* Keyword.Constant */
  .codehilite .kd { color: #b294bb} /* Keyword.Declaration */
  .codehilite .kn { color: #b294bb} /* Keyword.Namespace */
  .codehilite .kp { color: #b294bb} /* Keyword.Pseudo */
  .codehilite .kr { color: #b294bb} /* Keyword.Reserved */
  .codehilite .kt { color: #e3e7df} /* Keyword.Type */
  .codehilite .ld { color: #E4E4E4} /* Literal.Date */
  .codehilite .m { color: #f48c5f} /* Literal.Number */
  .codehilite .s { color: #b2bd67} /* Literal.String */
  .codehilite .na { color: #e65b67} /* Name.Attribute */
  .codehilite .nb { color: #f0c674} /* Name.Builtin */
  .codehilite .nc { color: #E4E4E4} /* Name.Class */
  .codehilite .no { color: #f48c5f} /* Name.Constant */
  .codehilite .nd { color: #E4E4E4} /* Name.Decorator */
  .codehilite .ni { color: #888a85} /* Name.Entity */
  .codehilite .ne { color: #E4E4E4} /* Name.Exception */
  .codehilite .nf { color: #fcaf3e} /* Name.Function */
  .codehilite .nl { color: #E4E4E4} /* Name.Label */
  .codehilite .nn { color: #E4E4E4} /* Name.Namespace */
  .codehilite .nx { color: #E4E4E4} /* Name.Other */
  .codehilite .py { color: #E4E4E4} /* Name.Property */
  .codehilite .nt { color: #e65b67} /* Name.Tag */
  .codehilite .nv { color: #ffffff} /* Name.Variable */
  .codehilite .ow { color: #E4E4E4} /* Operator.Word */
  .codehilite .w { color: #E4E4E4} /* Text.Whitespace */
  .codehilite .mf { color: #f48c5f} /* Literal.Number.Float */
  .codehilite .mh { color: #f48c5f} /* Literal.Number.Hex */
  .codehilite .mi { color: #f48c5f} /* Literal.Number.Integer */
  .codehilite .mo { color: #f48c5f} /* Literal.Number.Oct */
  .codehilite .sb { color: #E4E4E4} /* Literal.String.Backtick */
  .codehilite .sc { color: #E4E4E4} /* Literal.String.Char */
  .codehilite .sd { color: #E4E4E4} /* Literal.String.Doc */
  .codehilite .s2 { color: #b2bd67} /* Literal.String.Double */
  .codehilite .se { color: #E4E4E4} /* Literal.String.Escape */
  .codehilite .sh { color: #E4E4E4} /* Literal.String.Heredoc */
  .codehilite .si { color: #E4E4E4} /* Literal.String.Interpol */
  .codehilite .sx { color: #E4E4E4} /* Literal.String.Other */
  .codehilite .sr { color: #E4E4E4} /* Literal.String.Regex */
  .codehilite .s1 { color: #b2bd67} /* Literal.String.Single */
  .codehilite .ss { color: #E4E4E4} /* Literal.String.Symbol */
  .codehilite .bp { color: #E4E4E4} /* Name.Builtin.Pseudo */
  .codehilite .vc { color: #ffffff} /* Name.Variable.Class */
  .codehilite .vg { color: #ffffff} /* Name.Variable.Global */
  .codehilite .vi { color: #ffffff} /* Name.Variable.Instance */
  .codehilite .il { color: #f48c5f} /* Literal.Number.Integer.Long */

// icons
  .i {
    display: inline-block;
    vertical-align: middle;
  }

  .i-social {
    width: 16px;
    height: 16px;
    background: url('imgs/social-icons.png') no-repeat;
    background-size: 106px;

    &.flickr {
      background-position: 0 0;
    }

    &.lanyrd {
      background-position: -18px 0;
    }

    &.github {
      background-position: -36px 0;
    }

    &.twitter {
      background-position: -54px 0;
    }

    &.gplus {
      background-position: -72px 0;
    }

    &.rss {
      background-position: -90px 0;
    }
  }

// icon list
  .icon-list {
    margin: 0;
    padding: 0;
    list-style: none;

    & > li {
      margin: 0 0 0.3em;
    }

    & .i {
      margin-right: 4px;
    }
  }

// link list
  .link-list {
    & a {
      display: block;
    }
  }

// comments
  .comments {
    margin-top: 50px;
  }

// post preview
  .post-preview {
    @extend %clearfix;

    & h1 {
      margin-top: 0;

      & a:link,
      & a:visited {
        display: block;
        color: #fff;
      }
      & a:hover,
      & a:active {
        color: #fff;
        text-decoration: underline;
      }
    }

    & .preview-image {
      margin: 20px 0 0;

      @media screen and (min-width: $mobile-boundry) {
        float: left;
        width: 200px;
        margin: 5px 20px 20px 0;
      }
    }

    & .preview-image-sizer {
      position: relative;

      & img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
    }
  }

// pagination
  .pagination {
    overflow: hidden;
    margin: 2.1em 0;
    padding: 0;

    & li {
      display: inline;
    }

    & a:link,
    & a:visited,
    & .page,
    & .next,
    & .prev,
    & .gap {
      float: left;
      padding: 0 8px;
      font-weight: bold;
      border-right: 1px dotted #a5a5a5;
    }

    & .current,
    & .disabled,
    & .gap {
      color: #6e6e6e;
      font-weight: normal;
    }

    & .prev,
    & a.prev:link,
    & a.prev:visited {
      padding-left: 0;
    }

    & .next,
    & a.next:link,
    & a.next:visited {
      border: none;
    }
  }

// form rows
  .form-rows {
    margin: 1em -20px;

    .codehilite + & { // move these up against code examples
      margin-top: -1.1em;
    }

    @media screen and (min-width: $mobile-boundry) {
      margin-left: -32px;
      margin-right: 0;
    }

    & .field {
      display: table-row;

      &:nth-child(even) {
        & .label {
          background: #3CB39D;
        }
        & .input {
          background: #f7f7f7;
        }
      }
    }
    & .label {
      background: #009D81;
      color: #fff;
      vertical-align: middle;
      display: table-cell;
      width: 1px;
      white-space: nowrap;
      padding: 0.5em;
      padding-left: 20px;

      @media screen and (min-width: $mobile-boundry) {
        padding-left: 32px;
      }
    }
    & .input {
      background: #ECECEC;
      padding: 0 0.5em;
      vertical-align: middle;
      display: table-cell;
    }

    & input[type=text],
    & input[type=range] {
      width: 100%;
      margin: 0;
      @include box-sizing(border-box);
    }
  }

  .form-rows-inner {
    display: table;
    width: 100%;
  }

// quotes
  .quote {
    margin: 0;
    border-left: 10px solid #D5D5D5;
    padding-left: 16px;

    & > p:last-of-type {
      margin-bottom: 0;
    }
  }

// warning
  .warning {
    background: #BF0000;
    color: #fff;
    font-size: 0.8rem;
    font-weight: bold;

    padding: 6px 20px 5px 20px;
    margin: 0 0 0 -20px;

    @media screen and (min-width: $mobile-boundry) {
      padding: 6px 10px 5px 32px;
      margin-left: -32px;
      margin-right: -32px;
    }

    & > :first-child {
      margin-top: 0;
    }
    & > :last-child {
      margin-bottom: 0;
    }
  }

```
