### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gildata/RAIO#197]
# Tabs

![](http://img4.mukewang.com/59e8c78b00012b4f12800720.jpg)

http://www.imooc.com/video/3219

**Comment by xgqfrms-GitHub** [comment]
#  testTruthy

https://github.com/loiane/javascript-datastructures-algorithms/issues/31

```js


const testTruthy = (str = ``) => (str !== `` ? console.log(`truthy = ${str}`) : console.log(`falsy = ${str}`));


const testTruthy = (str = ``) => (str !== `` ? console.log(`truthy = ${str}`) : console.log(`falsy = ${str}`));

testTruthy(`abc`);
// truthy
testTruthy(``);
// falsy
testTruthy();
// falsy

```

**Comment by xgqfrms-GitHub** [comment]
# CSS3 animation

1. 位置， 下到上
2. 透明度，透明到不透明！

http://www.imooc.com/video/8232

![image](https://user-images.githubusercontent.com/18028768/31780928-af16abbc-b529-11e7-9c3e-1931d2267406.png)

**Comment by xgqfrms-GitHub** [comment]
# 使用JS，如何给下拉列表动态的添加一个option 选项？

http://www.imooc.com/article/10487


参考链接：
https://msdn.microsoft.com/en-us/library/dd757810(v=vs.85).aspx
http://www.cnblogs.com/duanhuajian/archive/2013/06/09/3129365.html
http://www.javascriptkit.com/jsref/select.shtml




```js

//1.动态创建select
function createSelect(){
    var mySelect = document.createElement("select");
    mySelect.id = "mySelect"; 
    document.body.appendChild(mySelect);
}

//2.添加选项option
function addOption(){
    //根据id查找对象，
    var obj=document.getElementById('mySelect');
    //添加一个选项
    obj.add(new Option("文本","值"));    //方法一：
    obj.options.add(new Option("text","value")); //方法二：
    for(var i=0;i<10;i++){
        obj.options[i]=new Option("新文本","新值");    //方法三：
    }
}

//3.删除所有选项option
function removeAll(){
    var obj=document.getElementById('mySelect');
    obj.options.length=0;
}

//4.删除一个选项option
function removeOne(){
    var obj=document.getElementById('mySelect');
    var index=obj.selectedIndex;    //index,要删除选项的序号
    obj.options.remove(index);
}

//5.获得选项option的值
var obj=document.getElementById('mySelect');
var index=obj.selectedIndex;     //序号，取当前选中选项的序号
var val = obj.options[index].value;

//6.获得选项option的文本
var obj=document.getElementById('mySelect');
var index=obj.selectedIndex;    
var val = obj.options[index].text;

//7.修改选项option
var obj=document.getElementById('mySelect');
var index=obj.selectedIndex;    
var val = obj.options[index]=new Option("新文本","新值");

//8.删除select
function removeSelect(){
    var mySelect = document.getElementById("mySelect");
    mySelect.parentNode.removeChild(mySelect);
}

```

**Comment by xgqfrms-GitHub** [comment]
#196 

http://www.imooc.com/article/4777

**Comment by xgqfrms-GitHub** [comment]
# `chrome://cache/`

```sh

chrome://cache/

chrome://view-http-cache/

```

**Comment by xgqfrms-GitHub** [comment]
# `:nth-of-type(n):hover + div.content {tarnsform: translateX()}`

???

no JS, just CSS!

http://www.imooc.com/video/3220

**Comment by xgqfrms-GitHub** [comment]
a:hover

.content{dispaly: block;}

**Comment by xgqfrms-GitHub** [comment]
# formatNumbersWithTitle

> bug

![image](https://user-images.githubusercontent.com/18028768/31802576-95e498ae-b581-11e7-84ae-394658f7d71d.png)

```js

/**
 * @author xgqfrms
 * @description formatNumbersWithTitle
 * 
 * @param {*} num 
 * @param {*} uid 
 * @param {*} debug 
 */



```

**Comment by xgqfrms-GitHub** [comment]
# 

> OK

![image](https://user-images.githubusercontent.com/18028768/31803499-aa8472de-b586-11e7-8bea-b85841470547.png)


```js

// format numbers



/**
 * @author xgqfrms
 * @description formatNumbersWithTitle
 * @created 2017.10.20
 * @param {* Number} num 
 * @param {* Boolean} debug 
 */


const formatNumbersWithTitle = (num = 1234567890.001, debug = false) => {
    let fn_str = ``,
        num_str = num.toString(),
        len = num_str.length,
        nl = Math.floor(len/3),//
        dot = num_str.indexOf(`.`),// -1 ???
        float = num_str.slice(dot !== -1 ? dot : len),
        int = num_str.slice(0, (dot !== -1 ? dot : len));
        result = `${int.substr(0, (len % 3 === 0) ? 3 : (len % 3))}`,// "1"
        temp = `${int.substr((len % 3 === 0 ? 3 : (len % 3)), len-3)}`;// ??? special case
    for (var i = 0; i < nl; i++) {
        if (i !== nl -1) {
                result += `,${temp.slice(0,3)}`;
        }else{
                result += `${temp.slice(0,3)}`;
        }
        temp = temp.slice(3);
    }
    fn_str = result + float;
    console.log(`result = `, result);
    console.log(`float = `, float);
    console.log(`fn_str = `, fn_str);
    // "1,234,567,890.001"
    // return fn_str;
    return fn_str;
};



/**
 * string to format number ???
 * #TODO
 * 
 * 
 * 
 */


```

**Comment by xgqfrms-GitHub** [comment]
# OK

![image](https://user-images.githubusercontent.com/18028768/31804085-bf627b08-b589-11e7-84c1-c35f0b0d8fec.png)



```js

// format numbers



/**
 * @author xgqfrms
 * @description formatNumbersWithTitle
 * @created 2017.10.20
 * @param {* Number} num 
 * @param {* Boolean} debug 
 */


const formatNumbersWithTitle = (num = 1234567890.001, debug = false) => {
    let fn_str = ``,
        num_str = num.toString(),
        len = num_str.length,
        nl = Math.floor(len/3),
        dot = num_str.indexOf(`.`),
        // -1 ???
        float = num_str.slice(dot !== -1 ? dot : len),
        int = num_str.slice(0, (dot !== -1 ? dot : len)),
        int_len = int.length,
        inl = Math.floor(int_len/3),
        result = `${int.substr(0, (int_len % 3 === 0) ? 3 : (int_len % 3))}`,// "12"
        temp = `${int.substr((int_len % 3 === 0 ? 3 : (int_len % 3)), int_len)}`;
        // len % 3 === 0 ??? special case
    console.log(`result = `, result);
    console.log(`int = `, int);
    console.log(`float = `, float);
    console.log(`temp = `, temp);
    for (var i = 0; i < inl; i++) {
        if (i !== inl - 1) {
                result += `,${temp.slice(0,3)}`;
        }else{
                result += `,${temp.slice(0,3)}`;
        }
        temp = temp.slice(3);
    }
    fn_str = result + float;
    console.log(`result = `, result);
    console.log(`fn_str = `, fn_str);
    // "1,234,567,890.001"
    copy(fn_str);
    return fn_str;
};




/**
 * string to format number ???
 * #TODO
 * 
 * 
 * 
 */



```

**Comment by xgqfrms-GitHub** [comment]
# full version

```js


/**
 * @author xgqfrms
 * @description formatNumbersWithTitle
 * @created 2017.10.20
 * 
 * @param {* Number} num 
 * @param {* data-*} uid 
 * @param {* Boolean} debug 
 */

const formatNumbersWithTitle = (num = 1234567890.001, uid = `[data-uid="fn-num"]`, debug = false) => {
    let fn_str = ``,
    num_str = num.toString(),
    len = num_str.length,
    nl = Math.floor(len/3),
    dot = num_str.indexOf(`.`),
    // -1 ???
    float = num_str.slice(dot !== -1 ? dot : len),
    int = num_str.slice(0, (dot !== -1 ? dot : len)),
    int_len = int.length,
    inl = Math.floor(int_len/3),
    result = `${int.substr(0, (int_len % 3 === 0) ? 3 : (int_len % 3))}`,// "12"
    temp = `${int.substr((int_len % 3 === 0 ? 3 : (int_len % 3)), int_len)}`;
    // len % 3 === 0 ??? special case
    if (debug) {
        console.log(`result = `, result);
        console.log(`int = `, int);
        console.log(`float = `, float);
        console.log(`temp = `, temp);
    }
    for (var i = 0; i < inl; i++) {
        result += `,${temp.slice(0,3)}`;
        temp = temp.slice(3);
    }
    fn_str = result + float;
    if (debug) {
        console.log(`result = `, result);
        console.log(`fn_str = `, fn_str);
        // "1,234,567,890.001"
    }
    copy(fn_str);
    return fn_str;
    /* 
        let fn_data = document.querySelector(uid);
        fn_data.setAttribute(`title`, fn_str);
        // undefined
        fn_data.attributes;
        // NamedNodeMap {0: data-uid, 1: title, length: 2}
        fn_data.hasAttribute(`title`);
        // true
        fn_data.getAttribute(`title`);
        // "1,234,567,890,.001"
        fn_data.removeAttribute(`title`);
        // undefined

    */
};


```

**Comment by xgqfrms-GitHub** [comment]
#  GraphQL提供数据接口新思路之数据聚合解决方案

> PPT

https://yq.aliyun.com/articles/225047

**Comment by xgqfrms-GitHub** [comment]
www.w3cschool.cn

**Comment by xgqfrms-GitHub** [comment]
https://ac.alloyteam.com/?_from=xgqfrms

**Comment by xgqfrms-GitHub** [comment]
# `nth-of-type(0)` ???

> `nth-of-type(1)`


https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type


```css

/* no :nth-of-type(0) ??? */

div.h5-dnd-icon-box:nth-of-type(1),
div.h5-dnd-icon-box:nth-of-type(2) {
    margin-top: 12px;
    background: #0ff;
}

div.h5-dnd-icon-box:nth-of-type(0) {
    background: #f0f;
}

```

![image](https://user-images.githubusercontent.com/18028768/31808818-648a4850-b5a7-11e7-9ba1-421cd3540c7e.png)

**Comment by xgqfrms-GitHub** [comment]
# Pure CSS Tabs

https://www.w3.org/TR/CSS22/selector.html

https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Selectors

https://www.sitepoint.com/css-selectors/

https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048

https://stackoverflow.com/questions/9836151/what-is-this-css-selector-class-span

**Comment by xgqfrms-GitHub** [comment]
https://www.w3.org/TR/CSS22/conform.html#doctree

# PURE CSS TABS

> JUST CSS, NO JS!

https://codepen.io/xgqfrms-gildata/pen/VMRbqL

http://cssmojo.com/pure-css-tab-panel/

https://codepen.io/thierry/pen/RrQpzK

# Pure CSS Functional Tabbed Area

https://www.css-tricks.com/examples/CSSTabs/radio.php


http://www.sevensignature.com/blog/code/responsive-pure-css-tabs/

# Responsive Pure CSS Tabs

http://www.sevensignature.com/blog/code/responsive-pure-css-tabs/
http://www.sevensignature.com/blog/demo/responsive-pure-css-tabs/


# A Pure CSS Approach to Tabs

https://trevan.co/a-pure-css-approach-to-tabs/

https://codepen.io/trevanhetzel/pen/Hmewv

**Comment by xgqfrms-GitHub** [comment]
# 兄弟选择器

http://www.w3school.com.cn/css/css_selector_adjacent_sibling.asp

http://www.cnblogs.com/anxiaoyu/p/7059443.html

http://makaidong.com/lvyueyang/828_11103311.html

**Comment by xgqfrms-GitHub** [comment]
http://html5doctor.com/element-index/

**Comment by xgqfrms-GitHub** [comment]
#  sass online compile

> SassMeister | The Sass Playground!

https://www.sassmeister.com/

https://www.ostraining.com/blog/coding/compiling-tools/

> Compile ◩ CSS PREprocessors

https://csspre.com/compile/

https://codepen.io/xgqfrms-gildata/pen/wrOexE

**Comment by xgqfrms-GitHub** [comment]
# CSS

```css

@import url(https://fonts.googleapis.com/css?family=Lato);
* {
    margin: 0;
    padding: 0;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

body {
    padding: 20px;
    text-align: left;
    font-family: Lato;
    color: #fff;
    background: #9b59b6;
}

h1 {
    font-weight: normal;
    font-size: 40px;
    font-weight: normal;
    text-transform: uppercase;
    float: left;
    margin: 20px 0 100px 10px;
}

h1 span {
    font-size: 13px;
    display: block;
    padding-left: 4px;
}

.tabs {
    width: 650px;
    float: none;
    list-style: none;
    position: relative;
    margin: 80px 0 0 10px;
    text-align: left;
}

.tabs li {
    float: left;
    display: block;
}

.tabs input[type="radio"] {
    position: absolute;
    top: 0;
    left: -9999px;
}

.tabs label {
    display: block;
    padding: 14px 21px;
    border-radius: 2px 2px 0 0;
    font-size: 20px;
    font-weight: normal;
    text-transform: uppercase;
    background: #8e44ad;
    cursor: pointer;
    position: relative;
    top: 4px;
    -moz-transition: all 0.2s ease-in-out;
    -o-transition: all 0.2s ease-in-out;
    -webkit-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
}

.tabs label:hover {
    background: #703688;
}

.tabs .tab-content {
    z-index: 2;
    display: none;
    overflow: hidden;
    width: 100%;
    font-size: 17px;
    line-height: 25px;
    padding: 25px;
    position: absolute;
    top: 53px;
    left: 0;
    background: #612e76;
}

.tabs [id^="tab"]:checked+label {
    top: 0;
    padding-top: 17px;
    background: #612e76;
}

.tabs [id^="tab"]:checked~[id^="tab-content"] {
    display: block;
}

p.link {
    clear: both;
    margin: 380px 0 0 15px;
}

p.link a {
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    color: #fff;
    padding: 5px 10px;
    margin: 0 5px;
    background-color: #612e76;
    -moz-transition: all 0.2s ease-in;
    -o-transition: all 0.2s ease-in;
    -webkit-transition: all 0.2s ease-in;
    transition: all 0.2s ease-in;
}

p.link a:hover {
    background-color: #522764;
}

```

> HTML

```html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pure CSS Tabs</title>
    <link rel="stylesheet" href="./pure-css-tabs.css">
</head>

<body>
    <h1>Pure CSS Tabs <span>Just CSS, No JS!</span></h1>
    <ul class="tabs" role="tablist">
        <li>
            <input type="radio" name="tabs" id="tab1" checked />
            <label for="tab1" role="tab" aria-selected="true" aria-controls="panel1" tabindex="0">Description</label>
            <div id="tab-content1" class="tab-content" role="tabpanel" aria-labelledby="description" aria-hidden="false">
                <p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
                    aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
            </div>
        </li>
        <li>
            <input type="radio" name="tabs" id="tab2" />
            <label for="tab2" role="tab" aria-selected="false" aria-controls="panel2" tabindex="0">Specification</label>
            <div id="tab-content2" class="tab-content" role="tabpanel" aria-labelledby="specification" aria-hidden="true">
                <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem
                    quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia
                    non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis
                    autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla?</p>
            </div>
        </li>
    </ul>
    <br style="clear: both;" />
    <p class="link">See the <a href="https://codepen.io/wallaceerick/pen/IGxim">3D Box</a> demo!</p>
</body>

</html>

```
