### ISSUE TITLE
多行文本溢出显示省略号(…) text-overflow: ellipsis 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gildata/RAIO#213]
# 多行文本溢出显示省略号(…) text-overflow: ellipsis 

https://c7sky.com/text-overflow-ellipsis-on-multiline-text.html

https://www.tuicool.com/articles/MB3amay
http://www.cnblogs.com/AllenChou/p/4706049.html

**Comment by xgqfrms-GitHub** [comment]
# MDN

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

https://css-tricks.com/almanac/properties/t/text-overflow/

# ??? last line `text-overflow: ellipsis`

>

**Comment by xgqfrms-GitHub** [comment]
https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-overflow_hover

**Comment by xgqfrms-GitHub** [comment]
https://stackoverflow.com/questions/17779293/css-text-overflow-ellipsis-not-working

# sort li


https://stackoverflow.com/questions/29721044/javascript-dom-using-nodelists-and-converting-to-an-array/29721090#29721090
https://stackoverflow.com/questions/29723088/sort-dom-elements-and-reinsert-them-into-a-ul
https://stackoverflow.com/questions/22157269/populate-array-value-from-li-elements-remove-hidden-li-from-array
https://stackoverflow.com/questions/35292733/ulli-sorting-not-working-in-ie-working-in-chrome
https://stackoverflow.com/questions/26685677/how-to-use-js-to-sort-li-by-todays-date

**Comment by xgqfrms-GitHub** [comment]
# background


> all in one

https://developer.mozilla.org/en-US/docs/Web/CSS/background

```css

background-image: none
background-position: 0% 0%
background-size: auto auto
background-repeat: repeat
background-origin: padding-box
background-clip: border-box
background-attachment: scroll
background-color: transparent

```

**Comment by xgqfrms-GitHub** [comment]
# Computed value 

https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value

https://developer.mozilla.org/zh-CN/docs/Web/CSS/computed_value

> StackOverflow

https://stackoverflow.com/questions/18412129/how-do-i-update-node-js-and-npm-on-windows

https://stackoverflow.com/users/5934465/xgqfrms

https://stackoverflow.com/search?q=user:5934465+[javascript]

**Comment by xgqfrms-GitHub** [comment]
https://repl.it/Es2T/1

https://stackoverflow.com/questions/41198746/how-to-understand-javascript-in-deep-with-var-scope-closure

**Comment by xgqfrms-GitHub** [comment]
https://www.python.org/shell/

https://www.pythonanywhere.com/

http://www.scipy.org/

https://www.djangoproject.com/
https://code.djangoproject.com/
https://github.com/scipy/scipy

https://www.python.org/events/python-events
https://github.com/django/django

https://www.pythonanywhere.com/user/gildata/consoles/6876277/

**Comment by xgqfrms-GitHub** [comment]
http://docs.python.org/3.6/tutorial/

**Comment by xgqfrms-GitHub** [comment]
http://windowsapp.pluralsight.com/Release/Releases/Setup.exe?utm_source=pluralsightappspage&utm_medium=Windows%20App

![image](https://user-images.githubusercontent.com/18028768/32490937-e097ea78-c3ef-11e7-8fc9-2c47f4ce2332.png)
> plurasight offline palyer
![image](https://user-images.githubusercontent.com/18028768/32491023-19b41cf0-c3f0-11e7-9750-e15648e68a79.png)

**Comment by xgqfrms-GitHub** [comment]
todo

**Comment by xgqfrms-GitHub** [comment]
# `:root`

https://developer.mozilla.org/zh-CN/docs/Web/CSS/:root

> `:root `这个 CSS 伪类匹配文档树的根元素。
对于 HTML 来说，`:root `表示 `<html>` 元素，除了优先级更高之外，与 html 选择器相同。

**Comment by xgqfrms-GitHub** [comment]
![image](https://user-images.githubusercontent.com/18028768/32527101-95b37ed2-c467-11e7-9407-4fa8b80acac1.png)

**Comment by xgqfrms-GitHub** [comment]
# css global var `:root`

```css

@charset "UTF-8";
.app {
    --bg-color: #000;
    --text-color: rgb(225, 11, 253);
}


/* :root === golbal var OK*/

 :root {
    --bg-color: #000;
    --text-color: #0f0;
}


/* bug ??? CSS var, local var can only using in the same context ??? */

.test-var {
    /* --bg-color: #000; */
    /* --text-color: #0f0; */
    color: var(--text-color);
    background-color: var(--bg-color);
}


/* :root === golbal var & reusable var */


/* 


    :root {
        --main-bg-color: brown;
    }

    .one {
        color: white;
        background-color: var(--main-bg-color);
        margin: 10px;
        width: 50px;
        height: 50px;
        display: inline-block;
    }

    .two {
        color: white;
        background-color: black;
        margin: 10px;
        width: 150px;
        height: 70px;
        display: inline-block;
    }

    .three {
        color: white;
        background-color: var(--main-bg-color);
        margin: 10px;
        width: 75px;
    }

    .four {
        color: white;
        background-color: var(--main-bg-color);
        margin: 10px;
        width: 100px;
    }

    .five {
        background-color: var(--main-bg-color);
    }

*/

```

**Comment by xgqfrms-gildata** [comment]
# whitespace ???

> `max-width: 80px;`

https://css-tricks.com/almanac/properties/w/whitespace/

# BAD


```css

table.fv-equity-pledge-table tr[data-tr="matrix-tr"]>td:nth-of-type(n+2) {
    width: 80px;
    // BAD
    line-height: 23px;
    height: 23px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    /* word-wrap: all; */
    /* color: red; */
    box-sizing: border-box;
    text-align: left;
}

```

![image](https://user-images.githubusercontent.com/29531779/33010640-2dccae48-ce16-11e7-80dc-d6948da4b05f.png)


#  OK

```css

table.fv-equity-pledge-table tr[data-tr="matrix-tr"]>td:nth-of-type(n+2) {
    // OK
    max-width: 80px;
    line-height: 23px;
    height: 23px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    /* word-wrap: all; */
    /* color: red; */
    box-sizing: border-box;
    text-align: left;
}

```

![image](https://user-images.githubusercontent.com/29531779/33010606-0d76fefa-ce16-11e7-9299-ed76df0330ee.png)

**Comment by xgqfrms-gildata** [comment]
# CSS: text-overflow: ellipsis

> CSS: multi-lines & ellipsis

https://github.com/gildata/RAIO/labels/CSS%3A%20text-overflow%3A%20ellipsis

https://github.com/gildata/RAIO/issues/213

```css
td.otc-big-event-reminder-table-td-value {
    box-sizing: border-box;
    /* width: 428px;
    min-width: 428px;
    max-width: 428px; */
    width: 438px;
    min-width: 438px;
    max-width: 438px;
    /* height: 46px;
    line-height: 46px; */
    height: 23px;
    line-height: 23px;
    font-size: 13px;
    text-align: left;
    padding-left: 6px;
}

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(2)>td.otc-big-event-reminder-table-td-value {
    height: 46px;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}

```

**Comment by xgqfrms** [comment]
# `ext-overflow: ellipsis` & `display: -webkit-box;`

> 多行文本溢出显示省略号(…) text-overflow: ellipsis

https://github.com/gildata/RAIO/issues/213

```css

.fv-important-infos-table-tbody>tr:nth-of-type(1)>td:last-child, .fv-important-infos-table-tbody>tr:nth-of-type(2)>td:last-child {
    background: #25292e;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    /* white-space: nowrap; */
    /* width: 400px; */
    /* height: calc(23px * 3); */
    box-sizing: border-box;
    /* height: 63px !important; */
    /* height: 77px !important; */
    line-height: 21px !important;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    /* font-size: 13px; */
    /* padding-top: 7px; */
    /* padding-bottom: 7px; */
    /* margin-top: 7px; */
    /* margin-bottom: 7px; */
    /* padding: 0; */
    padding-top: 4px;
    padding-bottom: 4px;
    /* position: relative; */
    border: 0;
    /* border-bottom: 1px solid #e9e9e9; */
}


```

**Comment by xgqfrms-GitHub** [comment]
http://www.cnblogs.com/xgqfrms/p/9139784.html

**Comment by xgqfrms-GitHub** [comment]
# OK

```css


.fixed-width {
    line-height: 36px;
    width: 610px;
    overflow: hidden;
    text-overflow: ellipsis;
    word-wrap: break-word;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
}

```

![image](https://user-images.githubusercontent.com/18028768/40962305-bfbe241a-68d7-11e8-86ca-8bfa192247fe.png)
