### ISSUE TITLE
Unix & Linux & Node.js

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#230]
# Linux & Node.js

> 

https://c9.io
https://c9.io/connect/github

```sh

```

**Comment by xgqfrms-gildata** [comment]
# onLine & offLine


```js
// get
const status = {
    // modules_name
    "stockfast01": {
        "index": 1,
        "show": true,
    },
    "news": {
        "index": 2,
        "show": false,
    }
};


// post

// localstorage

??? online/offline


https://www.sitepoint.com/offline-web-application-tutorial/
https://github.com/craigbuckler
http://blogs.sitepointstatic.com/examples/tech/offline/offline-example.zip


https://stackoverflow.com/questions/3181080/how-to-detect-online-offline-event-cross-browser

https://developer.mozilla.org/en-US/docs/Online_and_offline_events


navigator.onLine;
// true

https://developer.mozilla.org/en-US/docs/Web/Events/offline
https://developer.mozilla.org/en-US/docs/Web/Events/online

https://html.spec.whatwg.org/#event-offline


// standard event listeners
window.addEventListener("online", function() { ... });
window.addEventListener("offline", function() { ... });


window.localStorage & window.sessionStorage

// set a session value
window.sessionStorage.setItem("key", "my data");

// get a session value - returns "my data"
window.sessionStorage.getItem("key");


https://html.spec.whatwg.org/#mime-types-2


http://github.hubspot.com/offline/docs/welcome/
https://github.com/HubSpot/offline


https://www.html5rocks.com/en/mobile/workingoffthegrid/
https://www.html5rocks.com/en/tutorials/appcache/beginner/

https://www.html5rocks.com/zh/tutorials/webcomponents/imports/
https://www.html5rocks.com/en/tutorials/webcomponents/imports/

'import' in document.createElement('link');
// true

https://www.html5rocks.com/en/tutorials/webcomponents/template/
'content' in document.createElement('template');
// true



```

**Comment by xgqfrms-gildata** [comment]
https://www.google.com/chrome/browser/thankyou.html?statcb=1&extra=canarychannel

**Comment by xgqfrms-gildata** [comment]
# regex

https://regexper.com/

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

> tips

```js

    // 2012-10-18 = 2012/10/18
    announcement_date = announcement_date.replace(/-/gi, `/`);
    // start_date = start_date.replace(/-/gi, `/`); 
    // start_date = start_date.replace(/^(\d-\d)$/gi, '$1/$2');
    start_date = start_date.replace(/--/gi, 'XYZ');// temp var
    start_date = start_date.replace(/-/gi, `/`);
    start_date = start_date.replace(/XYZ/gi, `--`);// reset temp var
    // -- ??? //


```

**Comment by xgqfrms-gildata** [comment]
# whitespace ???

> `max-width: 80px;`

https://css-tricks.com/almanac/properties/w/whitespace/

# BAD


```css

table.fv-equity-pledge-table tr[data-tr="matrix-tr"]>td:nth-of-type(n+2) {
    width: 80px;
    // BAD
    line-height: 23px;
    height: 23px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    /* word-wrap: all; */
    /* color: red; */
    box-sizing: border-box;
    text-align: left;
}

```

![image](https://user-images.githubusercontent.com/29531779/33010640-2dccae48-ce16-11e7-80dc-d6948da4b05f.png)


#  OK

```css

table.fv-equity-pledge-table tr[data-tr="matrix-tr"]>td:nth-of-type(n+2) {
    // OK
    max-width: 80px;
    line-height: 23px;
    height: 23px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    /* word-wrap: all; */
    /* color: red; */
    box-sizing: border-box;
    text-align: left;
}

```

![image](https://user-images.githubusercontent.com/29531779/33010606-0d76fefa-ce16-11e7-9299-ed76df0330ee.png)
