### ISSUE TITLE
`break` and `continue`

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#261]
# JavaScript `break` and `continue`

1. The break statement "jumps out" of a loop.

2. The continue statement "jumps over" one iteration in the loop.

```js

// break

let text = ``;
for (let i = 0; i < 7; i++) {
    if(i === 3) {
        console.log(`break: will skip the whole loop!`, i);
        break;
    }else{
        text = `The number is ${i}`;
        console.log(`only output text that before break! =`, text);
    }
}

```

```js

// continue

let text = ``;
for (let i = 0; i < 7; i++) {
    if(i === 3) {
        console.log(`continue: only skip the current iteration!`, i);
        continue;
    }else{
        text = `The number is ${i}`;
        console.log(`text =`, text);
    }
}

```

**Comment by xgqfrms-gildata** [comment]
https://www.w3schools.com/js/js_break.asp

https://api.jquery.com/jQuery.each/

https://www.tutorialspoint.com/javascript/javascript_loop_control.htm

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/continue
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break

https://www.linkedin.com/learning/javascript-essential-training-3/break-and-continue-loops

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/33812312-5ed3cf5c-de57-11e7-8122-18457a21a843.png)

![image](https://user-images.githubusercontent.com/29531779/33812328-7baa2efa-de57-11e7-9186-bb5b136e12d1.png)

**Comment by xgqfrms-gildata** [comment]
# CSS Variables

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Variables

**Comment by xgqfrms-gildata** [comment]
# CSS Variables

https://drafts.csswg.org/css-variables/

https://developer.mozilla.org/en-US/docs/Web/CSS/--*


```html

<p id="firstParagraph">This paragraph should have a blue background and yellow text.</p>
<p id="secondParagraph">This paragraph should have a yellow background and blue text.</p>
<div id="container">
    <p id="thirdParagraph">This paragraph should have a green background and yellow text.</p>
</div>

```


```css
/* global variable */
:root {
    --first-color: #488cff;
    --second-color: #ffff8c;
}

#firstParagraph {
    background-color: var(--first-color);
    color: var(--second-color);
}

#secondParagraph {
    background-color: var(--second-color);
    color: var(--first-color);
}
/* local variable & overwrite*/
#container {
    --first-color: #48ff32;
}

#thirdParagraph {
    background-color: var(--first-color);
    color: var(--second-color);
}

```

**Comment by xgqfrms-gildata** [comment]
## font-family & @font-face

https://developer.mozilla.org/en-US/docs/Web/CSS/font
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size


```css

/* 1em === 16px */
/* 0.75em === 12px */

:root {
    font-size: 1em;
    /* font-size: 0.75em; */
    /* font-size: 12px; */
}

section{
    font-size: 1rem;
}

```

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family



```css

/* A font family name and a generic family name */
font-family: Gill Sans Extrabold, sans-serif;
font-family: "Goudy Bookletter 1911", sans-serif;

/* A generic family name only */
font-family: serif;
font-family: sans-serif;
font-family: monospace;
font-family: cursive;
font-family: fantasy;
font-family: system-ui;

/* Global values */
font-family: inherit;
font-family: initial;
font-family: unset;

```


https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-family
https://drafts.csswg.org/css-fonts-3/#font-family-desc

```css

@font-face {
    font-family: examplefont;
    src: url('examplefont.ttf');
}

```

**Comment by xgqfrms-gildata** [comment]
# em & rem & px

https://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/

http://pxtoem.com/

**Comment by xgqfrms-gildata** [comment]
# Chinese Standard Web Fonts:

> A Guide to CSS Font Family Declarations for Web Design in Simplified Chinese

http://www.kendraschaefer.com/2012/06/chinese-standard-web-fonts-the-ultimate-guide-to-css-font-family-declarations-for-web-design-in-simplified-chinese/

![image](https://user-images.githubusercontent.com/29531779/33813039-9211b8ca-de5c-11e7-99e8-7f3027bac289.png)

**Comment by xgqfrms-gildata** [comment]
```css

:root {
    font-size: 1em;
    /* font-size: 0.75em; */
    /* font-size: 12px; */
    --font-size: 12px;
    background: #fff;
    color: #000;
    font-family: "SimSun", serif, sans-serif;
    /* font-family: SimSun, serif, sans-serif; */
    /* simsun - bold */
    font-family: "Open Sans", sans-serif, Arial, Helvetica;
}
*{
    font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;
}
div{
    font-family: Georgia, "Times New Roman", "Microsoft YaHei", "微软雅黑", STXihei, "华文细黑", serif;
    font-family: Georgia, "Times New Roman", "Microsoft YaHei", 微软雅黑, STXihei, 华文细黑, serif;
    font-family: Arial, Helvetica, tahoma, verdana, 宋体, SimSun, 华文细黑, STXihei, sans-serif;
    font-family: Tahoma, Arial, Helvetica, "Microsoft YaHei New", "Microsoft Yahei", "微软雅黑", 宋体, SimSun, STXihei, "华文细黑", sans-serif;
    font-family: Georgia, "Times New Roman", "FangSong", "仿宋", STFangSong, "华文仿宋", serif;
}

```

**Comment by xgqfrms-gildata** [comment]
http://www.fontpalace.com/font-download/SimSun/

**Comment by xgqfrms-gildata** [comment]
https://github.com/gildata/UglifyJS-3/issues/3

**Comment by xgqfrms-gildata** [comment]
# browser-market-share

https://www.statista.com/statistics/272697/market-share-desktop-internet-browser-usa/

https://en.wikipedia.org/wiki/Usage_share_of_web_browsers

http://gs.statcounter.com/browser-market-share#monthly-201707-201707-map

https://yourbrowser.is/browser-market-share/2017/12/03/

**Comment by xgqfrms-gildata** [comment]
# bash & touch


![image](https://user-images.githubusercontent.com/29531779/33862805-83c35dd2-df1f-11e7-9e3a-f8dda3b1b58e.png)

**Comment by xgqfrms-gildata** [comment]
# 扩展程序 JSON Viewer

https://github.com/tulios/json-viewer

https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=zh-CN

chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/pages/options.html

```json
    // 
```

**Comment by xgqfrms-gildata** [comment]
# CSS: text-overflow: ellipsis

https://github.com/gildata/RAIO/labels/CSS%3A%20text-overflow%3A%20ellipsis

**Comment by xgqfrms-gildata** [comment]
# shit  【

![image](https://user-images.githubusercontent.com/29531779/33920071-f0e30a5c-dff6-11e7-81a1-433cf694fbf0.png)

**Comment by xgqfrms-gildata** [comment]
# Chinese Characters for Half

https://dictionary.hantrainerpro.com/chinese-english/translation-ban_half.htm
http://www.wearyourchinesename.com/chinese-symbols/chinese-symbols-h/chinese-symbol-for-half.html
http://zhongwen.com/

https://simple.wikipedia.org/wiki/Simplified_Chinese_characters

**Comment by xgqfrms-gildata** [comment]
# try catch

https://www.w3schools.com/js/js_errors.asp

**Comment by xgqfrms-gildata** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

**Comment by xgqfrms-gildata** [comment]
```js

try {
    let message = `handle json error!`,
        fileName = ``,
        lineNumber = ``;
    throw new Error(message, fileName, lineNumber);
    // new Error([message[, fileName[, lineNumber]]])
    // throw `Exception: \n handle json error!`;
} catch (err) {
    console.log(`catch error = \n`, err);
    console.log(`catch error.name = \n`, err.name);
    console.log(`catch error.message = \n`, err.message);
    console.log(`catch error.fileName = \n`, err.fileName);
    console.log(`catch error.lineNumber = \n`, err.lineNumber);
}

```

![image](https://user-images.githubusercontent.com/29531779/33923826-3be059ee-e00e-11e7-98e4-535838af6621.png)

**Comment by xgqfrms-gildata** [comment]
# OK

![image](https://user-images.githubusercontent.com/29531779/33924036-2301475c-e00f-11e7-800f-5a4549562984.png)


```js

function UserException(message = ``, fileName = ``, lineNumber = 0){
   this.message = message;
   this.fileName = fileName;
   this.lineNumber = lineNumber;
   this.name = 'UserException';
}

try {
    let message = `handle json error!`,
        fileName = `latest-transaction-data.js`,
        lineNumber = 29;
    throw new UserException(message, fileName, lineNumber);
    // new Error([message[, fileName[, lineNumber]]]);
} catch (err) {
    console.log(`catch error = \n`, err);
    console.log(`catch error.name = \n`, err.name);
    console.log(`catch error.message = \n`, err.message);
    console.log(`catch error.fileName = \n`, err.fileName);
    console.log(`catch error.lineNumber = \n`, err.lineNumber);
}




const UserException = (message = ``, fileName = ``, lineNumber = 0) => {
   this.message = message;
   this.fileName = fileName;
   this.lineNumber = lineNumber;
   this.name = 'UserException';
};
// TypeError: UserException is not a constructor


```

**Comment by xgqfrms-gildata** [comment]
```js

/**
 * @author xgqfrms 2017-12-13
 * @license MIT
 * @description Try-Catch-Throw-Error
 *
 * @param {*String } message
 * @param {*String } fileName
 * @param {*Number} lineNumber
 */



function UserException(message = ``, fileName = ``, lineNumber = 0){
    this.message = message;
    this.fileName = fileName;
    this.lineNumber = lineNumber;
    this.name = 'UserException';
 }

 try {
     let message = `handle json error!`,
         fileName = `latest-transaction-data.js`,
         lineNumber = 29;
     throw new UserException(message, fileName, lineNumber);
     // new Error([message[, fileName[, lineNumber]]]);
 } catch (err) {
     console.log(`catch error = \n`, err);
     console.log(`catch error.name = \n`, err.name);
     console.log(`catch error.message = \n`, err.message);
     console.log(`catch error.fileName = \n`, err.fileName);
     console.log(`catch error.lineNumber = \n`, err.lineNumber);
 }


```

**Comment by xgqfrms-gildata** [comment]
# ES6 Custom Error Class

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#ES6_Custom_Error_Class

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/33924345-a1cbe8de-e010-11e7-8047-b75b092e53d2.png)

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/33924822-a2b24df4-e012-11e7-9e92-1edc4417a6f6.png)

**Comment by xgqfrms-gildata** [comment]
# text-overflow

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

```css

*{
    overflow: hidden;
    white-space: nowrap;
    /* single line & nowrap */
}

*{
    box-sizing: border-box;
    width: 438px;
    height: 46px;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    /* multi lines & no need nowrap */
}

tbody.otc-company-news-table-tbody>tr.otc-company-news-table-tr>td:nth-of-type(1) {
    box-sizing: border-box;
    overflow: hidden;
    word-wrap: break-word;
    white-space: nowrap;
    text-overflow: ellipsis;
}

```

**Comment by xgqfrms-gildata** [comment]
# insertAdjacentHTML

```js


let html = `
    <a
        href="#${id}"
        title="${title}"
        data-title="${title}"
        data-link="fv-company-news-link"
        data-disabled="${id !== "null" ? false : true}"
        data-link-detail="company-news-link-detail-module"
        data-newsId="${id}">
        ${title}
    </a>
`;
dom.insertAdjacentHTML(`beforeend`, html);

```

**Comment by xgqfrms-gildata** [comment]
# table & thead

> OK

![image](https://user-images.githubusercontent.com/29531779/33979040-894bc996-e0dd-11e7-8631-1c2a26e73f02.png)


```css

thead.otc-research-report-table-thead {
    display: table-header-group;
}

tfoot.otc-research-report-table-tfoot {
    display: none;
}

```

> BAD

```css

thead.otc-company-bulletin-table-thead {
     display: block; 
    /*display: table;*/
}

tfoot.otc-company-bulletin-table-tfoot {
    display: none;
}

```
![image](https://user-images.githubusercontent.com/29531779/33979098-cd29af34-e0dd-11e7-8a20-5c67c4fd3d0f.png)

**Comment by xgqfrms-gildata** [comment]
# markman

http://getmarkman.com/#/download-modal

**Comment by xgqfrms-gildata** [comment]
# table & colspan

https://www.w3schools.com/TAGS/att_td_colspan.asp

> colspan

https://www.w3.org/TR/html401/struct/tables.html
https://www.w3.org/TR/html401/struct/tables.html#adef-colspan

**Comment by xgqfrms-gildata** [comment]
# table & multi vertical  cells

> how to cross html table multi vertical  cells

https://www.w3.org/WAI/tutorials/tables/multi-level/
https://www.w3.org/TR/html401/struct/tables.html

**Comment by xgqfrms-gildata** [comment]
# table 

> multi vertical cells


![image](https://user-images.githubusercontent.com/29531779/34022134-7e9f2fe2-e178-11e7-821d-a03612bd9c9a.png)

![image](https://user-images.githubusercontent.com/29531779/34022147-95af2b7e-e178-11e7-9904-34912971f340.png)



https://www.w3.org/TR/html401/struct/tables.html


```html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <table border="1" summary="This table gives some statistics about fruit
                 flies: average height and weight, and percentage
                 with red eyes (for both males and females).">
        <caption><em>A test table with merged cells</em></caption>
        <tr>
            <th rowspan="2">
                <th colspan="2">Average
                    <th rowspan="2">Red<br/>eyes
                        <tr>
                            <th>height
                                <th>weight
                                    <tr>
                                        <th>Males
                                            <td>1.9
                                                <td>0.003
                                                    <td>40%
                                                        <tr>
                                                            <th>Females
                                                                <td>1.7
                                                                    <td>0.002
                                                                        <td>43%
    </table>
</body>

</html>

```

**Comment by xgqfrms-gildata** [comment]
# table & `rowspan`

> rowspan="2"

![image](https://user-images.githubusercontent.com/29531779/34022195-cde00130-e178-11e7-9c08-0cfb37d10232.png)

**Comment by xgqfrms-gildata** [comment]
# "rowspan & colspan" 


https://github.com/gildata/RAIO/issues/229#issuecomment-345888013

**Comment by xgqfrms-gildata** [comment]
# CSS: table & th,td & `headers="blank"` & `headers="co1 c1"`

```md

CSS: table & th,td & `headers="blank"` & `headers="co1 c1"`

```

**Comment by xgqfrms-gildata** [comment]
# Table & rowspan & scroll


![image](https://user-images.githubusercontent.com/29531779/34022949-48d16434-e17d-11e7-9be5-73d1b8baf375.png)


```html


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>colspan & rowspan</title>
    <style>
        h1.title {
            /* text-align: center; */
            margin-left: 150px;
        }
        
        [data-div="div"] {
            box-sizing: border-box;
            width: 320px;
            max-height: 200px;
            overflow-y: scroll;
        }
        
        [data-div="h1"] {
            margin-left: 30px;
        }
    </style>
</head>

<body>
    <section>
        <div>
            <h1 class="title">colspan & rowspan</h1>
        </div>
    </section>
    <table border="1" summary="This table gives some statistics about fruit flies: average height and weight, and percentage with red eyes (for both males and females).">
        <caption><em>A test table with merged cells</em></caption>
        <tr>
            <th rowspan="2">rowspan="2"</th>
            <th colspan="2">Average</th>
            <th rowspan="5">
                <div data-div="div">
                    <h1 data-div="h1">rowspan="5"</h1>
                    <p>
                        table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br>
                    </p>
                    <p>
                        table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br>
                    </p>
                    <p>
                        table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br> table-colspan-rowspan <br>
                    </p>
                </div>
            </th>
        </tr>
        <tr>
            <th>height</th>
            <th>weight</th>
        </tr>
        <tr>
            <th>Males</th>
            <td>1.9</td>
            <td>0.003</td>
        </tr>
        <tr>
            <th>Females</th>
            <td>1.7</td>
            <td>0.002</td>
        </tr>
        <tr>
            <th>UFO</th>
            <td>x.y</td>
            <td>0.000</td>
        </tr>
    </table>
</body>

</html>

```
![image](https://user-images.githubusercontent.com/29531779/34022947-46bcd99e-e17d-11e7-8fdb-cb1dbd6f6de8.png)

**Comment by xgqfrms-gildata** [comment]
# CSS hack

```css

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(2)>td.otc-big-event-reminder-table-td-value,
[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(3)>td.otc-big-event-reminder-table-td-value {
    box-sizing: border-box;
    height: 46px;
    line-height: 23px;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(2)>td.otc-big-event-reminder-table-td-value {
    border-right: 1px solid #f5f5f5;
}

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(3)>td.otc-big-event-reminder-table-td-value {
    border-right: 1px solid #fff;
}


/* overwrite */

tbody.otc-big-event-reminder-table-tbody>tr:nth-of-type(2) {
    border-right: 1px solid #d7dbe0;
}

tbody.otc-big-event-reminder-table-tbody>tr:nth-of-type(3) {
    border-right: 1px solid #d7dbe0;
}


```
