### ISSUE TITLE
CSS hack

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#265]
# CSS hack

```css

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(2)>td.otc-big-event-reminder-table-td-value,
[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(3)>td.otc-big-event-reminder-table-td-value {
    box-sizing: border-box;
    height: 46px;
    line-height: 23px;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(2)>td.otc-big-event-reminder-table-td-value {
    border-right: 1px solid #f5f5f5;
}

[data-tbody="otc-big-event-reminder-table-tbody"]>tr.otc-big-event-reminder-table-tr:nth-of-type(3)>td.otc-big-event-reminder-table-td-value {
    border-right: 1px solid #fff;
}


/* overwrite */

tbody.otc-big-event-reminder-table-tbody>tr:nth-of-type(2) {
    border-right: 1px solid #d7dbe0;
}

tbody.otc-big-event-reminder-table-tbody>tr:nth-of-type(3) {
    border-right: 1px solid #d7dbe0;
}


```

# bug

![image](https://user-images.githubusercontent.com/29531779/34025293-04da7060-e18a-11e7-808e-4bccd41c95bc.png)

# OK

![image](https://user-images.githubusercontent.com/29531779/34025308-1a15d8de-e18a-11e7-971d-f5be3f0f9fd7.png)
