### ISSUE TITLE
table overflow scroll

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#273]
# table overflow scroll

https://stackoverflow.com/questions/14834198/table-scroll-with-html-and-css

**Comment by xgqfrms-gildata** [comment]
# bug

![image](https://user-images.githubusercontent.com/29531779/34381349-fd518456-eb42-11e7-8be0-21e3d713f35a.png)

**Comment by xgqfrms-gildata** [comment]
http://jsfiddle.net/4SUP8/1/

**Comment by xgqfrms-gildata** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

**Comment by xgqfrms-gildata** [comment]
# remove table

> no data

![image](https://user-images.githubusercontent.com/29531779/34397214-0eacf764-ebaf-11e7-8043-9e8ff9672a51.png)

**Comment by xgqfrms-gildata** [comment]
# plotOptions & dataLabels & zIndex


> plotOptions.line.dataLabels.zIndex

https://api.highcharts.com/highcharts/plotOptions.line.dataLabels.zIndex

**Comment by xgqfrms-gildata** [comment]
#  minRange

https://api.highcharts.com/highcharts/xAxis.minRange

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/minrange/

**Comment by xgqfrms-gildata** [comment]
https://api.highcharts.com/highcharts/xAxis.units

**Comment by xgqfrms-gildata** [comment]
# tickAmount: 80

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/tickamount/

**Comment by xgqfrms-gildata** [comment]
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/startofweek-monday/

**Comment by xgqfrms-gildata** [comment]
# bug ???

![image](https://user-images.githubusercontent.com/29531779/34399199-16499dd6-ebc0-11e7-9f3a-0e7ed63656fb.png)

**Comment by xgqfrms-gildata** [comment]
ppt

![image](https://user-images.githubusercontent.com/29531779/34401843-d0c355fe-ebd8-11e7-957a-7baf8cf9e391.png)

**Comment by xgqfrms-gildata** [comment]
```js

// numericSymbols: ['k', 'M', 'G', 'T', 'P', 'E'],
                // numericSymbols: ['千', '百万', '十亿', '兆', '千兆', '百万兆'],
                numericSymbols: ['千', '00万', '0亿', '兆', '千兆', '百万兆'],

```

**Comment by xgqfrms-gildata** [comment]
# how to modify css var value


https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
https://developer.mozilla.org/en-US/docs/Web/CSS/var

https://www.w3.org/TR/css-variables-1/

**Comment by xgqfrms-gildata** [comment]
# CSS-Variable


```js


let elem = document.getElementById("alert"),
    theCSSprop = window.getComputedStyle(elem, null).getPropertyValue("--color").trim(),
    msgElt = document.getElementById("computed_style");

msgElt.innerHTML = "The alert div's color is \"<span style='color:" + theCSSprop + "'>" + theCSSprop +'</span>".';

function changeDocColor() {
    elem.style.setProperty('--color', 'var(--new-color)');
}

```

**Comment by xgqfrms-gildata** [comment]
1. css var & style.setProperty

2. js load ? skin css

3. HC/HS , pass skin global var

**Comment by xgqfrms-gildata** [comment]
https://codepen.io/xgqfrms-gildata/pen/dJvRzE
https://www.htmlgoodies.com/html5/css/a-guide-to-using-css-variables.html

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/34428315-5da7083c-ec86-11e7-86d1-282549c3be8b.png)
![image](https://user-images.githubusercontent.com/29531779/34428316-620a37f0-ec86-11e7-9cae-1ec030107eea.png)

**Comment by xgqfrms-gildata** [comment]
#  set-name-of-file-downloaded-from-browser

https://stackoverflow.com/questions/3102226/how-to-set-name-of-file-downloaded-from-browser

**Comment by xgqfrms-gildata** [comment]
where is the title come form?

![image](https://user-images.githubusercontent.com/29531779/34431952-14921948-ecae-11e7-970f-3c2841aea1e6.png)

**Comment by xgqfrms-gildata** [comment]
# table & scrollbar

http://jsfiddle.net/4SUP8/1/

**Comment by xgqfrms-gildata** [comment]
# CSS & var


## calc var

> `font-size: calc(var(--font-size-factor) * 1em);`

```css

@charset "UFT-8";

/* @media print */


/* @media screnn */

:root {
    /* % & rem & em */
    --fontSizeRemBase: 0.75rem;
    --fontSizeEmBase: 0.75em;
    --fontSize12: 12px;
    --fontSizeP75: 75%;
    --fontSize16: 16px;
    --color: #fff;
    --background: #fff;
    --backgroundBlack: #000;
    /* js change color value */
    --red: #f00;
    --green: #0f0;
    --blue: #0f0;
    --white: #fff;
    --black: #000;
    --font-size-factor: 2.5;
}

body {
    color: var(--color);
    font-size: var(--fontSizeEmBase);
}

[data-title="h1"] {
    /* font-size: var(--fontSize12*2); */
    font-size: calc(var(--font-size-factor) * 1em);
}

table {
    color: var(--color);
}

```
