### ISSUE TITLE
CSS3 data-* Selector & Multi Tables bug

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#276]
# CSS3 data-* Selector & Multi Tables bug

![image](https://user-images.githubusercontent.com/29531779/34477066-860c55ae-efd1-11e7-8e09-a5374d8a5094.png)

https://codepen.io/xgqfrms-gildata/pen/KZqqww

**Comment by xgqfrms-gildata** [comment]
# modal
> html, css, js

https://codepen.io/xgqfrms-gildata/pen/baRRby

**Comment by xgqfrms-gildata** [comment]
# OK

![image](https://user-images.githubusercontent.com/29531779/34477217-2d4f5e64-efd3-11e7-8335-1686ae00ad4b.png)


```html

```


```css

@charset "UTF-8";

/* table bug ??? */

[data-section="data-table-box"]:nth-of-type(1) {
    background: rgb(6, 238, 255);
}

[data-section="data-table-box"]:nth-of-type(2) {
    background: rgb(250, 205, 6);
}

[data-section="data-table-box"]:nth-of-type(1)>table>tbody {
    /* border: 1px solid #f00; */
    background: #f00;
}

[data-section="data-table-box"]:nth-of-type(2)>table>tbody {
    /* border: 1px solid #f0f; */
    background: #0f0;
}

table:nth-of-type(1) {
    /* border: 1px solid #f00; */
}

table:nth-of-type(2) {
    /* border: 1px solid #f0f; */
}

[data-tbody="otc-equity-shareholder-table-tbody"]:nth-of-type(1) {
    /* background: #f00; */
}

[data-tbody="otc-equity-shareholder-table-tbody"]:nth-of-type(2) {
    /* background: #0f0; */
}

[data-div="div-box"]:nth-of-type(1) {
    background: #f0f;
}

[data-div="div-box"]:nth-of-type(2) {
    background: #0ff;
}

[data-div="div-box"]:nth-of-type(3) {
    background: #ff0;
}

```

**Comment by xgqfrms-gildata** [comment]
# modal-plugin

> building-your-own-javascript-modal-plugin

https://scotch.io/tutorials/building-your-own-javascript-modal-plugin

**Comment by xgqfrms-gildata** [comment]
https://codepen.io/kenwheeler/pen/fLptb/
https://codepen.io/kenwheeler/pen/HfwAt/
https://codepen.io/kenwheeler/pen/LvGjK/

**Comment by xgqfrms-gildata** [comment]
# highcharts-background-color

https://stackoverflow.com/questions/20731153/changing-highcharts-background-color

**Comment by xgqfrms-gildata** [comment]
https://api.highcharts.com/highcharts/colors

https://api.highcharts.com/highcharts/chart.backgroundColor
https://api.highcharts.com/highcharts/plotOptions.area.color

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/34482167-5390aa24-eff1-11e7-8432-53b9385b70dd.png)

**Comment by xgqfrms-gildata** [comment]
https://api.highcharts.com/highcharts/colors
https://api.highcharts.com/highcharts/chart.backgroundColor
https://api.highcharts.com/highcharts/chart.style
https://api.highcharts.com/highcharts/colorAxis
https://www.highcharts.com/docs/chart-design-and-style/style-by-css
https://api.highcharts.com/highcharts/plotOptions.area.fillColor

# css demo ???

> color & skin

**Comment by xgqfrms-gildata** [comment]
https://github.com/scotch-io/javascript-modal
https://scotch.io/tutorials/building-your-own-javascript-modal-plugin

**Comment by xgqfrms-gildata** [comment]
https://raventools.com/blog/create-a-modal-dialog-using-css-and-javascript/

https://www.w3schools.com/howto/howto_css_modals.asp

https://www.w3schools.com/howto/howto_css_modal_images.asp
https://www.w3schools.com/howto/howto_js_lightbox.asp

**Comment by xgqfrms-gildata** [comment]
https://codepen.io/xgqfrms-gildata/pen/EovaKR

**Comment by xgqfrms-gildata** [comment]
# Sass (.scss) Playground

https://www.sassmeister.com/

**Comment by xgqfrms-gildata** [comment]
# JS Playground

https://jscomplete.com/repl/

**Comment by xgqfrms-gildata** [comment]
# css minify bug???

> .css !== .js

![image](https://user-images.githubusercontent.com/29531779/34512795-773e538c-f09f-11e7-9221-2d32064fa066.png)

**Comment by xgqfrms-gildata** [comment]
# extract-text-webpack-plugin

https://www.npmjs.com/package/sass-loader#in-production
https://github.com/webpack-contrib/extract-text-webpack-plugin#extract-text-plugin

```sh
# for webpack 3

$ npm i -D extract-text-webpack-plugin





# for webpack 2
npm install --save-dev extract-text-webpack-plugin@2.1.2

# for webpack 1
npm install --save-dev extract-text-webpack-plugin@1.0.1

```

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/34513056-273a2cd8-f0a1-11e7-9de8-8fe2e87f1028.png)

**Comment by xgqfrms-gildata** [comment]
# bug ???

> Error: Cannot find module 'webpack/lib/Chunk'

![image](https://user-images.githubusercontent.com/29531779/34513129-88d25498-f0a1-11e7-9a55-8d5a5e6b842f.png)

**Comment by xgqfrms-gildata** [comment]
# webpack configuration object  & error!

![image](https://user-images.githubusercontent.com/29531779/34513249-50e2d232-f0a2-11e7-9175-c04400d6166b.png)

**Comment by xgqfrms-gildata** [comment]
# bad

![image](https://user-images.githubusercontent.com/29531779/34513282-8ab8f90a-f0a2-11e7-9f74-20a5277b0e9a.png)


# ok


![image](https://user-images.githubusercontent.com/29531779/34513526-9d75f632-f0a3-11e7-88d9-4b9632bdac1a.png)

**Comment by xgqfrms-gildata** [comment]
# .publicPath

https://github.com/webpack-contrib/extract-text-webpack-plugin#extract

![image](https://user-images.githubusercontent.com/29531779/34513626-2161ecda-f0a4-11e7-8a40-9d0a70731d0a.png)

https://github.com/webpack-contrib/extract-text-webpack-plugin#multiple-instances

https://github.com/webpack-contrib/extract-text-webpack-plugin#extracting-sass-or-less

https://github.com/webpack-contrib/extract-text-webpack-plugin#url-resolving

**Comment by xgqfrms-gildata** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin#modify-filename

# public-path & code-splitting

https://webpack.js.org/guides/public-path/
https://webpack.js.org/guides/code-splitting/


https://stackoverflow.com/questions/36470442/webpack-file-loader-duplicate-public-path
https://stackoverflow.com/questions/36733540/extract-scss-to-css-using-webpack

**Comment by xgqfrms-gildata** [comment]
https://webpack.js.org/guides/getting-started/
https://webpack.js.org/guides/output-management/

**Comment by xgqfrms-gildata** [comment]
https://webpack.js.org/plugins/extract-text-webpack-plugin/
https://webpack.js.org/guides/output-management/
https://webpack.js.org/configuration/output/

> manifest.json

https://github.com/danethurber/webpack-manifest-plugin

https://webpack.js.org/configuration/output/

**Comment by xgqfrms-gildata** [comment]
https://webpack.js.org/configuration/output/#output-publicpath

https://webpack.js.org/configuration/output/#output-path


https://stackoverflow.com/questions/28846814/what-does-publicpath-in-webpack-do

# `output.path` & `output.publicPath`

![image](https://user-images.githubusercontent.com/29531779/34514472-8c6f8e8e-f0a8-11e7-907e-6c58c5c97ef4.png)

**Comment by xgqfrms-gildata** [comment]
https://github.com/vikingmute/vikingmute.github.com/commit/b46399a532edce8a5889bf9300f644905e20537f

https://github.com/vikingmute/webpack-for-fools
http://vikingmute.com/

**Comment by xgqfrms-gildata** [comment]
https://github.com/vikingmute/webpack-for-fools/blob/master/entries/chapter-2.md

https://github.com/vikingmute/webpack-for-fools/blob/master/entries/newchapter-2.md

**Comment by xgqfrms-gildata** [comment]
# uglify & options

https://www.npmjs.com/package/uglifyjs-webpack-plugin#uglifyoptions
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/master#uglifyoptions

https://github.com/mishoo/UglifyJS2/tree/harmony#minify-options

**Comment by xgqfrms-gildata** [comment]
# how to change page skin?


https://angular.cn/

**Comment by xgqfrms007** [comment]
# js & skin

> js 实现网页换肤功能

http://www.haorooms.com/post/js_changeshin

**Comment by xgqfrms007** [comment]
https://github.com/confidence68
https://github.com/confidence68/Tic-Tac-Toe_byexam
https://github.com/confidence68/mobile_touchload_mohuSearch

http://www.haorooms.com/post/js_changeshin
http://www.haorooms.com/post/es_modules
https://ponyfoo.com/articles/es6-modules-in-depth
http://www.haorooms.com/post/2017_webdesigngw
http://www.haorooms.com/post/iphonex_shipei

**Comment by xgqfrms007** [comment]
https://github.com/confidence68
https://github.com/confidence68/Tic-Tac-Toe_byexam
https://github.com/confidence68/mobile_touchload_mohuSearch

http://www.haorooms.com/post/css_preload
http://www.haorooms.com/post/js_changeshin
http://www.haorooms.com/post/es_modules
https://ponyfoo.com/articles/es6-modules-in-depth
http://www.haorooms.com/post/2017_webdesigngw
http://www.haorooms.com/post/iphonex_shipei

**Comment by xgqfrms007** [comment]
http://www.zhangxinxu.com/wordpress/2017/09/css-shapes-outside-iphone-x-head/

**Comment by xgqfrms007** [comment]
http://www.haorooms.com/post/css_preload
https://www.w3.org/TR/preload/
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Preloading_content

**Comment by xgqfrms007** [comment]
http://www.haorooms.com/post/css_preload
https://www.w3.org/TR/preload/
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Preloading_content

**Comment by xgqfrms007** [comment]
# caniuse css3 shape

https://caniuse.com/

https://tests.caniuse.com/?feat=css-shapes

https://stackoverflow.com/questions/20676293/can-we-give-a-shadow-to-a-custom-css3-shape

https://getflywheel.com/layout/create-shapes-css3/

**Comment by xgqfrms007** [comment]
https://caniuse.com/#index

https://caniuse.com/#info_news

https://caniuse.com/issue-list

https://caniuse.com/#feat=css-shapes

https://caniuse.com/usage-table

https://github.com/fyrd/caniuse

**Comment by xgqfrms007** [comment]
https://www.w3.org/TR/css-shapes/

**Comment by xgqfrms007** [comment]
# CSS bg

```css
body {
  background-color:#556;
  background-image: linear-gradient(30deg, #445 12%, transparent 12.5%, transparent 87%, #445 87.5%, #445),
  linear-gradient(150deg, #445 12%, transparent 12.5%, transparent 87%, #445 87.5%, #445),
  linear-gradient(30deg, #445 12%, transparent 12.5%, transparent 87%, #445 87.5%, #445),
  linear-gradient(150deg, #445 12%, transparent 12.5%, transparent 87%, #445 87.5%, #445),
  linear-gradient(60deg, #99a 25%, transparent 25.5%, transparent 75%, #99a 75%, #99a), 
  linear-gradient(60deg, #99a 25%, transparent 25.5%, transparent 75%, #99a 75%, #99a);
  background-size:80px 140px;
  background-position: 0 0, 0 0, 40px 70px, 40px 70px, 0 0, 40px 70px;
  
  font-family: 'Prompt', sans-serif;
}

```

https://codepen.io/chriscoyier/pen/MeJWoM

https://codepen.io/xgqfrms007/pen/goxmXa
