### ISSUE TITLE
multi tables & css data-* bug

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#284]
# multi tables & css data-* bug

> solution

1. each table with an unique id/data-uid

2.  warp table in a container ??? bug 

```css

table[data-tables="otc-equity-shareholder-table2"]>tbody.otc-equity-shareholder-table-tbody>tr.otc-equity-shareholder-table-tr>td.otc-equity-shareholder-table-td-value:nth-of-type(4) {
    text-align: left;
}

table[data-tables="otc-equity-shareholder-table2"]>tbody.otc-equity-shareholder-table-tbody>tr.otc-equity-shareholder-table-tr>td.otc-equity-shareholder-table-td-value:nth-of-type(5) {
    text-align: left;
}

```
