### ISSUE TITLE
css tricks & user-scalable

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#315]
# css tricks user-scalable

https://css-tricks.com/snippets/html/responsive-meta-tag/

https://css-tricks.com/probably-use-initial-scale1/

https://css-tricks.com/forums/topic/maximum-scale1-user-scalableno/

**Comment by xgqfrms-gildata** [comment]
https://stackoverflow.com/questions/22777734/what-is-initial-scale-user-scalable-minimum-scale-maximum-scale-attribute-in

https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/37751820-803ac354-2dcf-11e8-8563-f7a371fcdb98.png)

## Q:  js 如何避免多次重复绑定？

## A: HTML5 & dataset & flag

**Comment by xgqfrms-gildata** [comment]
# scroll & customize style

![image](https://user-images.githubusercontent.com/29531779/37751868-cf4c6c4a-2dcf-11e8-8b93-9bd3b9c2dc4e.png)

![image](https://user-images.githubusercontent.com/29531779/37751869-d3c0ba7e-2dcf-11e8-908a-0ca2a0ccacc2.png)



```css

@charset "UTF-8";

/* @import url("./scrollbar.css"); */


/* scrollbar & must be set this!*/

::-webkit-scrollbar {
    box-sizing: border-box;
}


/* vertical & decrement */

::-webkit-scrollbar-button:vertical:decrement {
    background: url("../img/arrow-up.png") 4px 3px no-repeat;
    background-color: #2c3237;
}

::-webkit-scrollbar-button:vertical:decrement:hover {
    background: url("../img/arrow-up-hover.png") 4px 3px no-repeat;
    background-color: #2c3237;
    ;
    /* background-color: #3c4247; */
}


/* vertical & increment */

::-webkit-scrollbar-button:vertical:increment {
    background: url("../img/arrow-down.png") 4px 3px no-repeat;
    background-color: #2c3237;
}

::-webkit-scrollbar-button:vertical:increment:hover {
    background: url("../img/arrow-down-hover.png") 4px 3px no-repeat;
    background-color: #2c3237;
}


/* horizontal & increment */

::-webkit-scrollbar-button:horizontal:increment {
    background: url("../img/arrow-right.png") 4px 3px no-repeat;
    background-color: #2c3237;
}

::-webkit-scrollbar-button:horizontal:increment:hover {
    background: url("../img/arrow-right-hover.png") 4px 3px no-repeat;
    background-color: #2c3237;
}


/* horizontal & decrement */

::-webkit-scrollbar-button:horizontal:decrement {
    background: url("../img/arrow-left.png") 4px 3px no-repeat;
    background-color: #2c3237;
}

::-webkit-scrollbar-button:horizontal:decrement:hover {
    background: url("../img/arrow-left-hover.png") 4px 3px no-repeat;
    background-color: #2c3237;
}


/* thumb */

::-webkit-scrollbar-thumb {
    height: 10px;
    background-color: #4a4a4a;
    opacity: 1;
}

::-webkit-scrollbar-thumb:hover {
    background-color: #212529;
    cursor: pointer;
}

::-webkit-scrollbar-thumb:active {
    background-color: #4a4a4a;
    cursor: pointer;
}


/* track */

::-webkit-scrollbar-track {
    background-color: #2c3237;
    opacity: 1;
}


/* corner */

::-webkit-scrollbar-corner {
    background-color: #3c4247;
}

```
