### ISSUE TITLE
test & mocha

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#318]
# mocha

https://github.com/mochajs/mocha

**Comment by xgqfrms-gildata** [comment]
https://stackoverflow.com/questions/8332333/node-js-setting-up-environment-specific-configs-to-be-used-with-everyauth

**Comment by xgqfrms-gildata** [comment]
# enzyme

https://github.com/airbnb/enzyme

**Comment by xgqfrms-gildata** [comment]
https://github.com/topics/javascript

https://github.com/topics/node.js

**Comment by xgqfrms-gildata** [comment]
https://github.com/thedaviddias/Front-End-Checklist
https://frontendchecklist.io/

**Comment by xgqfrms-gildata** [comment]
https://github.com/MaximAbramchuck/awesome-interview-questions

https://github.com/yangshun/front-end-interview-handbook

https://github.com/GetStoryline/awesome-alexa

https://github.com/Chalarangelo/30-seconds-of-code

https://github.com/ryanmcdermott/clean-code-javascript

https://github.com/elsewhencode/project-guidelines

https://github.com/i0natan/nodebestpractices

**Comment by xgqfrms-gildata** [comment]
# react & tree component

https://github.com/react-component/tree

https://react-component.github.io/tree/

**Comment by xgqfrms-gildata** [comment]
https://react.rocks/?q=tree

https://react.rocks/example/react-treebeard

https://github.com/alexcurtis/react-treebeard
https://github.com/alexcurtis/react-treebeard/issues/125

https://alexcurtis.github.io/react-treebeard/

https://github.com/pqx/react-ui-tree
https://pqx.github.io/react-ui-tree/

**Comment by xgqfrms-gildata** [comment]
https://github.com/gildata/RAIO/issues/24

**Comment by xgqfrms-gildata** [comment]
https://github.com/gildata/ARTC/issues/1

**Comment by xgqfrms-gildata** [comment]
# default.js

> change skin

![image](https://user-images.githubusercontent.com/29531779/38183328-39e94e7e-3672-11e8-9d93-0465993f796f.png)


![image](https://user-images.githubusercontent.com/29531779/38183324-351ae448-3672-11e8-94c6-f536b4cc88d3.png)

**Comment by xgqfrms-gildata** [comment]
# JSON ECMA 404

> double quotes

![image](https://user-images.githubusercontent.com/29531779/38183345-5305cd60-3672-11e8-9059-a0b47a32da66.png)

**Comment by xgqfrms-gildata** [comment]
# Link & react-router-dom

```jsx

import {
    BrowserRouter as Router,
    Route,
    Link
} from 'react-router-dom';

```


https://stackoverflow.com/questions/36394539/react-router-link-how-to-trigger-a-click-event-on-a-link-from-another-component

**Comment by xgqfrms-gildata** [comment]
https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf
https://css-tricks.com/learning-react-router/
https://www.techiediaries.com/react-router-dom-v4/
https://scotch.io/tutorials/routing-react-apps-the-complete-guide

**Comment by xgqfrms-gildata** [comment]
https://github.com/scotch-io/react-routing/blob/master/src/Common/main.component.jsx
https://github.com/christiannwamba/scotch-react-router

**Comment by xgqfrms-gildata** [comment]
http://knowbody.github.io/react-router-docs/api/Link.html

> active color & Link

![image](https://user-images.githubusercontent.com/29531779/38188449-a6801024-368e-11e8-99b9-126ffa16f0b5.png)

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/38190050-1fa8f7e4-3695-11e8-8644-bffcb73898a0.png)

**Comment by xgqfrms-gildata** [comment]
https://ant.design/components/table/#API

**Comment by xgqfrms-gildata** [comment]
https://ant.design/components/table/#Column

table 只能设置 表格的 thead, 无法 设置 td ???

https://ant.design/components/table/#

![image](https://user-images.githubusercontent.com/29531779/38194318-641fdbe0-36a9-11e8-9bee-881dc398b151.png)

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/38195684-54cc1192-36b1-11e8-9deb-fcb8000de01f.png)

**Comment by xgqfrms-gildata** [comment]
# java

http://www.oracle.com/technetwork/java/javase/terms/readme/java-readme-366167.html

**Comment by xgqfrms-gildata** [comment]
# shaped data

![image](https://user-images.githubusercontent.com/29531779/38230612-5488b678-3741-11e8-9a1b-85f9237b2787.png)



```js

const obj = {
    "pjbz": "债券评级",
    "pjjgcs": 21698,
    "pjbzcs": 0,
    "fbrq": "2017-06-22",
    "xypj": "AAA",
    "pjzw": "--",
    "bdfx": "维持",
    "pjjg": "大公国际资信评估有限公司",
    "pjlx": "长期信用评级",
    "lspjbd": "查看", // data-datas="21698,0,查看"
},

// "pjjgcs": 21698,
// "pjbzcs": 0,
// "lspjbd": "查看",
if (obj.lspjbd !== undefined && obj.pjjgcs !== undefined && obj.pjbzcs !== undefined) {
    let x = obj.pjjgcs,
        y = obj.pjbzcs,
        z = obj.lspjbd,
        re_shaped_data = `${x}${y}${z}`;
    let html = `
        <td data-datas="${re_shaped_data}">查看</td>
    `;
    const IP = window.parent.location.origin;
    const url = `/webservice/webf9/bond/lsbd?{"GilCode": ${gilcode}, "OrgCode": ${y}}, "Stand": ${x}`;
}


// "lspjbd": "21698,0,查看",
if (obj.lspjbd !== undefined) {
    let shaped_data = obj.lspjbd.split(`,`);
    let html = `
        <td data-datas="${[...shaped_data]}">查看</td>
    `;
    const IP = window.parent.location.origin;
    const url = `/webservice/webf9/bond/lsbd?{"GilCode": ${gilcode}, "OrgCode": ${shaped_data[0]}}, "Stand": ${haped_data[1]}`;
}

```

**Comment by xgqfrms-gildata** [comment]
http://nswbmw.com/
https://github.com/nswbmw/N-blog

**Comment by xgqfrms-gildata** [comment]
https://github.com/alsotang/node-lessons

**Comment by xgqfrms-gildata** [comment]
# Open New Window HTML Content 

> blank window


https://codepen.io/gildata/pen/VrzXOb

**Comment by xgqfrms-gildata** [comment]
# es6 destructuring object & rename key & gildata

>Rename & Destructure Variables in ES6

https://github.com/gildata/RAIO/issues/217

http://wesbos.com/destructuring-renaming/

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/38287116-88b2c244-37fb-11e8-9247-8a82c8190581.png)

# NodeList to Array

> ES6 & Destructure

**Comment by xgqfrms-gildata** [comment]
# table & css bug

> border-collapse: collapse; 

去掉后，table border = 0 就可以了。

![image](https://user-images.githubusercontent.com/29531779/38293738-322bdf08-381b-11e8-901a-e91b486c28f5.png)

**Comment by xgqfrms-gildata** [comment]
```css

@charset "UFT-8";

/* modules */

.bonds-module-box-5 {
    box-sizing: border-box;
}

.bonds-h5dnd-modules-title-box {
    box-sizing: border-box;
    width: 100%;
    max-width: 1100px;
    height: 25px;
    line-height: 25px;
    margin: 0 auto;
    background-color: #fff;
}

.bonds-h5dnd-modules-title {
    box-sizing: border-box;
    width: 100%;
    margin: 0 auto;
    position: relative;
    color: #2e2f33;
    text-indent: 14px;
    margin-left: 0;
    font-weight: 600;
    font-size: 15px;
    margin-top: 6px;
    margin-bottom: 5px;
    /* font-family: "MicroSoft YaHei", sans-serif, serif; */
    font-family: SimSun, serif, sans-serif;
}

.bonds-h5dnd-modules-title::before {
    position: absolute;
    top: 3px;
    left: 0px;
    content: "";
    display: inline-block;
    width: 4px;
    background: #f70;
    height: 15px;
}


/* basic-information-interest-rates-debt-bonds */

html,
body,
section,
div,
table {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
}

thead,
tfoot,
tr,
td {
    padding: 0;
    margin: 0;
    border: 0;
}

div,
ul,
li,
a {
    box-sizing: border-box;
    margin: 0px;
    padding: 0px;
}


/* table */

.bonds-table {
    box-sizing: border-box;
    color: #4d4d4d;
    background: #fff;
    border: 1px solid #c5d2db;
    font-weight: normal;
    width: 100%;
    max-width: 1100px;
    overflow: auto;
    margin: 5px auto;
    border-spacing: 0;
    border-collapse: collapse;
}

@media screen and (max-width: 480px) {
    .bonds-table {
        font-size: 12px;
        /* color: #f00; */
    }
}

@media screen and (min-width: 1080px) {
    .bonds-table {
        /* font-size: 23px; */
        /* color: #f0f; */
        font-size: 12px;
    }
}


/* thead & tfoot */

.bonds-table-thead {
    display: table-header-group;
}

.bonds-table-tr>.bonds-table-th-value {
    text-align: left;
    padding-left: 8px;
    font-size: 12px;
    /* font-weight: normal; */
}

.bonds-table-td-title {
    background: #e8eefa;
    text-align: center;
}

.bonds-table-tfoot {
    display: none;
}


/* tbody & tr */

.bonds-table-tbody>tr:nth-of-type(2n-1) {
    background: #f5f5f5;
}

.bonds-table-tbody>tr:nth-of-type(2n) {
    background: #fff;
}

.bonds-table-tbody>tr.bonds-table-tr {
    /* border: 1px solid #e9e9e9; */
}

.bonds-table-tbody>tr.bonds-table-tr:nth-of-type(2n-1)>td.bonds-table-td-value {
    /* border-top: 1px solid #e9e9e9; */
}

.bonds-table-tbody>tr.bonds-table-tr:nth-of-type(2n)>td.bonds-table-td-value {
    /* border-top: 1px solid #e9e9e9; */
}

.bonds-table-tbody>tr.bonds-table-tr:nth-last-of-type(2)>td.bonds-table-td-value {
    border-bottom: 0;
}

.bonds-table-tbody>tr.bonds-table-tr:nth-last-of-type(1) {
    /* border-top: 0; */
    /* border-bottom: 1px solid #e9e9e9; */
}

.bonds-table-tbody>tr.bonds-table-tr:nth-last-of-type(1)>td:nth-last-of-type(2) {
    /* border-top: 2px solid #c5d2db; */
}


/* tr */

.bonds-table-tr {
    box-sizing: border-box;
    height: 25px;
    line-height: 25px;
}


/* long text */

.bonds-table-tr>td.bonds-table-td-key {
    box-sizing: border-box;
    overflow: hidden;
    word-wrap: break-word;
    white-space: nowrap;
    text-overflow: ellipsis;
    border: 1px solid #c5d2db;
}

.bonds-table-tr>td.bonds-table-td-value {
    box-sizing: border-box;
    border-top: 1px solid #e9e9e9;
    border-bottom: 1px solid #e9e9e9;
}


/* td */

.bonds-table-tr>td {
    box-sizing: border-box;
    height: 23px;
    line-height: 23px;
    font-size: 12px;
    font-family: SimSun, serif, sans-serif;
    /* border: 1px solid #f0f; */
}

.bonds-table-td-key {
    background: #e8eefa;
    color: #4d4d4d;
    /* padding-left: 8px; */
    text-indent: 8px;
    width: 160px;
    min-width: 50px;
    max-width: 160px;
}

.bonds-table-td-value {
    /* padding-left: 8px; */
    text-indent: 8px;
    width: auto;
    min-width: 100px;
    max-width: 300px;
}


/* no data */

[data-display="display-none"] {
    display: none;
}


/* excel */

[data-excel*="excel"] {
    position: relative;
    padding-left: 4px;
    float: right;
    /* margin-right: 50px; */
    line-height: 20px;
    height: 20px;
    box-sizing: border-box;
    width: 50px;
}

[data-excel*="excel"]>a:hover {
    color: #f50;
}

[data-excel*="excel"]>a {
    text-decoration: none;
    color: #3285ff;
    font-size: 12px;
    font-weight: normal;
    padding-left: 3px;
}

[data-excel*="excel"]>a::before {
    position: absolute;
    left: 1px;
    top: 1px;
    background-image: url(./xyz/excel.png), url(./excel.png), url(../../img/excel.png);
    background-position: 0px 0px;
    background-repeat: no-repeat;
    width: 16px;
    height: 16px;
    content: "";
    display: block;
    cursor: default;
}


/* others */

[data-span="data-otc-ES-title"] {
    color: red;
}

[data-title-text="bonds-basic-information-interest-rates-debt-bonds-title-text"] {
    color: #4d4d4d;
    font-size: 12px;
    font-weight: normal;
}

```
