### ISSUE TITLE
fixed table header css

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#319]
# fixed table header css

http://salzerdesign.com/test/fixedTable.html

https://stackoverflow.com/questions/19559197/how-to-make-scrollable-table-with-fixed-headers-using-css

**Comment by xgqfrms-gildata** [comment]
http://jsfiddle.net/7UZA4/1385/

1. thead block

2. tbody scroll

**Comment by xgqfrms-gildata** [comment]
# sort table

http://tablesorter.com/docs/#Demo

**Comment by xgqfrms-gildata** [comment]
# scroll to top

https://stackoverflow.com/questions/1144805/scroll-to-the-top-of-the-page-using-javascript-jquery

**Comment by xgqfrms-gildata** [comment]
> bad

![image](https://user-images.githubusercontent.com/29531779/38465941-4a375bae-3b54-11e8-8009-93e58ec32cde.png)

> ok

![image](https://user-images.githubusercontent.com/29531779/38465945-5855f704-3b54-11e8-87cd-930de70a86ba.png)

**Comment by xgqfrms-gildata** [comment]
# bootstrap modal & css var()

https://getbootstrap.com/docs/4.0/components/modal/

![image](https://user-images.githubusercontent.com/29531779/38466483-74cbdb4e-3b5c-11e8-815b-42b772d281cf.png)

```scss

:root {
  // Custom variable values only support SassScript inside `#{}`.
  @each $color, $value in $colors {
    --#{$color}: #{$value};
  }

  @each $color, $value in $theme-colors {
    --#{$color}: #{$value};
  }

  @each $bp, $value in $grid-breakpoints {
    --breakpoint-#{$bp}: #{$value};
  }

  // Use `inspect` for lists so that quoted items keep the quotes.
  // See https://github.com/sass/sass/issues/2383#issuecomment-336349172
  --font-family-sans-serif: #{inspect($font-family-sans-serif)};
  --font-family-monospace: #{inspect($font-family-monospace)};
}

```

**Comment by xgqfrms-gildata** [comment]
# ES6 & module & import & script

http://2ality.com/2017/01/import-operator.html

**Comment by xgqfrms-gildata** [comment]
# xshell bug

> 3o days

![image](https://user-images.githubusercontent.com/29531779/38467000-8f5b30d8-3b64-11e8-9828-7f273cf8821f.png)

https://www.netsarang.com/download/down_xsh5.html?token=K1l4YXpoczBBV1Ard1Y5WS9NMU5od0ByOEU3Tis1Unlwd3FiQXJiU3ovMmNn 

![image](https://user-images.githubusercontent.com/29531779/38467006-b20432ba-3b64-11e8-9aa4-77940b9a80ea.png)

**Comment by xgqfrms-gildata** [comment]
# xshell edu

https://www.netsarang.com/download/down_xsh5.html?token=WmhuYkd0VEw5YTlmUm54bkVkYzZnd0ByOEU3Tis1Unlwd3FiQXJiU3ovMmNn

https://cdn.netsarang.net/26be7d08/Xshell-5.0.1339p.exe

**Comment by xgqfrms-gildata** [comment]
https://softwaresdaily.com/xshell-5/

**Comment by xgqfrms-gildata** [comment]
# Google Chrome

https://en.wikipedia.org/wiki/Google_Chrome_version_history
https://en.wikipedia.org/wiki/Google_Chrome

> 2013 & Blink

https://en.wikipedia.org/wiki/Blink_(web_engine)

https://www.google.cn/chrome/index.html
https://www.google.cn/chrome/thankyou.html?statcb=1&installdataindex=defaultbrowser

**Comment by xgqfrms-gildata** [comment]
# Xshell 5

https://www.netsarang.com/products/xsh_overview.html

**Comment by xgqfrms-gildata** [comment]
# DOMContentLoaded

https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

```js

document.addEventListener(`DOMContentLoaded`, () => {
    const url = `${IP}${PATH}${gilcode}`;
    showTableData(url);
});

```

**Comment by xgqfrms-gildata** [comment]
# 全角（  => 半角 (

![image](https://user-images.githubusercontent.com/29531779/38481454-78f0989e-3bfd-11e8-9689-96307c3d13ff.png)

```js

x = `这种全角的（ 能不能换成半角的(`;
x.replace(/（ /ig, `(`);
// "这种全角的(能不能换成半角的"
y = `这种（ 全角的（ 能不能换成（ 半角的（ `;
y.replace(/（ /ig, `(`);
// "这种(全角的(能不能换成(半角的("

```

**Comment by xgqfrms-gildata** [comment]
# NG2

http://easings.net/zh-cn

http://reactivex.io/

**Comment by xgqfrms-gildata** [comment]
shit zh-Hans chart

**Comment by xgqfrms-gildata** [comment]
# superTables.css & fixed header table & table-designs

http://jsfiddle.net/fVtyD/2/

https://css-tricks.com/complete-guide-table-element/

https://css-tricks.com/fixing-tables-long-strings/

https://www.smashingmagazine.com/2008/08/top-10-css-table-designs/

***


# web speed test

http://www.speedtest.net/result/7211478404

https://fast.com/

![image](https://user-images.githubusercontent.com/29531779/38485874-e2e31186-3c0d-11e8-888c-4705a363350a.png)


# vertical-align

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

**Comment by xgqfrms-gildata** [comment]
# Super Tables
> css

```css

/*
/////////////////////////////////////////////////////////////////////////////////////////
// Super Tables v0.30 - MIT Style License
// Copyright (c) 2008 Matt Murphy --- www.matts411.com
//
// Contributors:
// Joe Gallo
/////////////////////////////////////////////////////////////////////////////////////////
*/

.sBase {
    position: relative;
    width: 100%;
    height: 100%;
    overflow: hidden;
    TEXT-ALIGN: left;
}


/* HEADERS */

.sHeader {
    position: absolute;
    z-index: 3;
    background-color: #fff;
}

.sHeaderInner {
    position: relative;
}

.sHeaderInner table {
    border-spacing: 0px 0px !important;
    border-collapse: collapse !important;
    width: 1px !important;
    table-layout: fixed !important;
    /*background-color: #ffffff;  Here b/c of Opera 9.25 :(*/
}


/* HEADERS - FIXED */

.sFHeader {
    position: absolute;
    z-index: 4;
    overflow: hidden;
}

.sFHeader table {
    border-spacing: 0px 0px !important;
    border-collapse: collapse !important;
    width: 1px !important;
    table-layout: fixed !important;
    background-color: #ffffff;
    /* Here b/c of Opera 9.25 :( */
}


/* BODY */

.sData {
    position: absolute;
    z-index: 2;
    overflow: auto;
    /*background-color: #ffffff;*/
}

.sData table {
    border-spacing: 0px 0px !important;
    border-collapse: collapse !important;
    width: 1px !important;
    table-layout: fixed !important;
}


/* BODY - FIXED */

.sFData {
    position: absolute;
    z-index: 1;
    /*background-color: #ffffff;*/
}

.sFDataInner {
    position: relative;
}

.sFData table {
    border-spacing: 0px 0px !important;
    border-collapse: collapse !important;
    width: 1px !important;
    table-layout: fixed !important;
}


/*
/////////////////////////////////////////////////////////////////////////////////////////
// Super Tables - Skin Classes
// Remove if not needed
/////////////////////////////////////////////////////////////////////////////////////////
*/


/* sDefault */

.sDefault {
    margin: 0px;
    padding: 0px;
    border: none;
}

.sDefault th,
.sDefault td {
    border: 1px solid #cccccc;
    padding: 3px 6px 3px 4px;
    white-space: nowrap;
}

.sDefault th {
    background-color: #e5e5e5;
    border-color: #c5c5c5;
}

.sDefault-Fixed {
    background-color: #eeeeee;
    border-color: #c5c5c5;
}


/* sSky */

.sSky {
    margin: 0px;
    padding: 0px;
    border: none;
    font-family: "Microsoft YaHei", sans-serif;
    font-size: 13px;
}

.sSky th,
.sSky td {
    border: 1px solid #9eb6ce;
    padding: 3px 6px 3px 4px;
    white-space: nowrap;
}

.sSky th {
    background-color: #CFDCEE;
}

.sSky-Fixed {
    background-color: #015ca3 !important;
    color: #fff;
}

.sSky-Fixed td {
    border: none !important;
}


/* sOrange */

.sOrange {
    margin: 0px;
    padding: 0px;
    border: none;
    font-family: "Microsoft YaHei", sans-serif;
    font-size: 13px;
}

.sOrange th,
.sOrange td {
    border: 1px solid #d7dbe0;
    padding: 3px 6px 3px 4px;
    white-space: nowrap;
}

.sOrange th {
    background-color: #e8eefa;
}

.sOrange-Fixed {
    background-color: #e8eefa;
}

.sOrange-change {
    background-color: #f7ede4;
}


/* sDark */

.sDark {
    margin: 0px;
    padding: 0px;
    border: none;
    font-family: "Microsoft YaHei", sans-serif;
    font-size: 14px;
    color: #ffffff;
}

.sDark th,
.sDark td {
    border: 1px solid #555555;
    padding: 3px 6px 3px 4px;
    white-space: nowrap;
}

.sDark th {
    background-color: #000000;
}

.sDark-Fixed {
    background-color: #222222;
}

.sDark-Main {
    background-color: #333333;
}

```
