### ISSUE TITLE
Modern Modular JavaScript Design Patterns

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#320]
# Modern Modular JavaScript Design Patterns

https://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript

# ESLint

https://eslint.org/docs/2.0.0/rules/no-unused-vars

https://eslint.org/docs/2.0.0/rules/indent

**Comment by xgqfrms-gildata** [comment]
https://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript
http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html

**Comment by xgqfrms-gildata** [comment]
# js pdf & js blogs

https://www.javascriptcn.com/thread-2.html
https://www.javascriptcn.com/thread-list.html

**Comment by xgqfrms-gildata** [comment]
# class & super

![image](https://user-images.githubusercontent.com/29531779/38596572-e43dca80-3d84-11e8-9c8d-290df64c9e9f.png)

> class default constructor ???

![image](https://user-images.githubusercontent.com/29531779/38596642-47759e34-3d85-11e8-8299-113f129a0dd5.png)


```js

```

**Comment by xgqfrms-gildata** [comment]
# pagination & table

> codepen

https://codepen.io/search/pens?q=pagination&limit=all&type=type-pens

https://codepen.io/search/pens?q=table&order=popularity&depth=everything&show_forks=false


## Javascript Pagination

https://codepen.io/karpovsystems/pen/fFHxK

**Comment by xgqfrms-gildata** [comment]
# Transfer 穿梭框 

>Transfer 穿梭框  & 双栏穿梭选择框

https://ng.ant.design/#/components/transfer

![image](https://user-images.githubusercontent.com/29531779/38605171-25a1b872-3da5-11e8-9f77-02a65bee2696.png)

**Comment by xgqfrms-gildata** [comment]
# polyfill & `startsWith`


https://github.com/mathiasbynens/String.prototype.startsWith

**Comment by xgqfrms-gildata** [comment]
# safari

![image](https://user-images.githubusercontent.com/29531779/38608378-bf328130-3dad-11e8-897a-1ea89b7cb5b4.png)

> 开启 Safari 调试工具

https://developer.apple.com/safari/tools/


https://jingyan.baidu.com/article/cb5d61050860e2005c2fe024.html

**Comment by xgqfrms-gildata** [comment]
# bootstrap

> drag & drop

http://www.layoutit.cn/

**Comment by xgqfrms-gildata** [comment]
# TortoiseSVN

> 针对 Windows 平台的 Subversion 客户端  & Version 1.9

https://tortoisesvn.net/docs/release/TortoiseSVN_zh_CN/index.html

![image](https://user-images.githubusercontent.com/29531779/38653456-6ef944ac-3e3d-11e8-9921-4b27f8c89144.png)

https://tortoisesvn.net/support.html

>检出

https://tortoisesvn.net/docs/release/TortoiseSVN_zh_CN/tsvn-cli-main.html#tsvn-cli-checkout
https://tortoisesvn.net/docs/release/TortoiseSVN_zh_CN/tsvn-cli-main.html#tsvn-cli-checkmods

**Comment by xgqfrms-gildata** [comment]
https://tortoisesvn.net/docs/release/TortoiseSVN_zh_CN/tsvn-repository.html#tsvn-serversetup-local-dia-1

**Comment by xgqfrms-gildata** [comment]
# css var & bootstrap4

> scrimba

https://scrimba.com/

https://github.com/scrimba/community/blob/master/FAQ.md#what-is-scrimba

https://scrimba.com/g/gbootstrap4


> 文件被另一个程序占用无法移动修改如何解决

https://jingyan.baidu.com/article/b2c186c806d84ec46ef6ffb0.html

**Comment by xgqfrms-gildata** [comment]
#  Bootstrap v4.1.0 & css var()

https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.css

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

```css

/*!
 * Bootstrap v4.1.0 (https://getbootstrap.com/)
 * Copyright 2011-2018 The Bootstrap Authors
 * Copyright 2011-2018 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
:root {
    --blue: #007bff;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
    --white: #fff;
    --gray: #6c757d;
    --gray-dark: #343a40;
    --primary: #007bff;
    --secondary: #6c757d;
    --success: #28a745;
    --info: #17a2b8;
    --warning: #ffc107;
    --danger: #dc3545;
    --light: #f8f9fa;
    --dark: #343a40;
    --breakpoint-xs: 0;
    --breakpoint-sm: 576px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;
    --font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}

*,
*::before,
*::after {
    box-sizing: border-box;
}

html {
    font-family: sans-serif;
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -ms-overflow-style: scrollbar;
    -webkit-tap-highlight-color: transparent;
}


```

**Comment by xgqfrms-gildata** [comment]
# PC 如何 链接手机 调试移动网站 

> Chrome To Mobile

https://www.zhihu.com/question/20322475

http://wetest.qq.com/cloud/index.php/help/cloudindex

https://chrome.google.com/webstore/detail/chrome-to-mobile/idknbmbdnapjicclomlijcgfpikmndhd

http://people.apache.org/~pmuellr/weinre/docs/latest/

**Comment by xgqfrms-gildata** [comment]
# vpn

> VPN上不去的真正原因

http://club.qingdaonews.com/showAnnounce_2_5602047_1_0.htm

**Comment by xgqfrms-gildata** [comment]
# Javascript Pagination

https://codepen.io/xgqfrms-gildata/pen/zWbZPX

**Comment by xgqfrms-gildata** [comment]
# how to change CSS `:root` value?



# `:root`

https://developer.mozilla.org/en-US/docs/Web/CSS/:root

>  In HTML, `:root` represents the `<html>` element and is identical to the selector `html`, except that its specificity is higher.

> `在 HTML 中,: 根表示<html>元素, 它与选择器 html 相同, 只是它的特异性较高。</html>`


## `:root` === `html`

https://www.w3schools.com/cssref/sel_root.asp

> The `:root` selector matches the document's root element. In HTML, the root element is always the html element.


```js

html = document.querySelector(`html`);

html.style.color;
// ""
html.style.getPropertyValue("--color");
// ""
getComputedStyle(html).getPropertyValue("--color");
// " red"


html.body;
// undefine
html.children;
// HTMLCollection(2) [head, body]

body = html.lastElementChild;
// body
body.style.color;
// ""
body.style.getPropertyValue("--color");
// ""
getComputedStyle(body).getPropertyValue("--color");
// " red"





getComputedStyle(html).getPropertyValue("--new-color");
// " green"
getComputedStyle(body).getPropertyValue("--new-color");
// " green"




// html.style.setProperty('--color', '--new-color');
// bad, must be var!
html.style.setProperty('--color', 'var(--new-color)');
// html === :root


getComputedStyle(html).getPropertyValue("--color");
// " green"
getComputedStyle(body).getPropertyValue("--color");
// " green"


body.style.setProperty('--color', '#f0f');

getComputedStyle(html).getPropertyValue("--color");
// " green"
getComputedStyle(body).getPropertyValue("--color");
// "#f0f"



// children overwwrite parent

// inline style & style="--color:#f0f;"


html.style.setProperty('--color', '#ff0');

getComputedStyle(html).getPropertyValue("--color");
// "#ff0"
getComputedStyle(body).getPropertyValue("--color");
// "#f0f"


```




***

## CSS3 variables

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables


https://developer.mozilla.org/en-US/docs/Web/CSS/var


```css


.two {
    color: var(--my-var, red);
    /* Red if --my-var is not defined */
}

.three {
    background-color: var(--my-var, var(--my-background, pink));
    /* pink if my-var and --my-background are not defined */
}

.three {
    background-color: var(--my-var, --my-background, pink);
    /* Invalid: "--my-background, pink" */
}


```

```js

// get variable from inline style
element.style.getPropertyValue("--my-var");

// get variable from wherever
getComputedStyle(element).getPropertyValue("--my-var");

// set variable on inline style
element.style.setProperty("--my-var", jsVar + 4)


```
