### ISSUE TITLE
webpack & base64 image

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#321]
# webpack & base64 image

> 

```sh

$ npm i -D url-loader file-loader

```

https://medium.com/a-beginners-guide-for-webpack-2/handling-images-e1a2a2c28f8d

**Comment by xgqfrms-gildata** [comment]
# data Urls

https://css-tricks.com/data-uris/

# autoprefixer ???

>css autoprefixer

**Comment by xgqfrms-gildata** [comment]
## issues

> `https://github.com/b-tiwari/react-ts-mobx-bootstrap/issues/2`

**Comment by xgqfrms-gildata** [comment]
thereby  === 从而 & thru/through === 通过

**Comment by xgqfrms-gildata** [comment]
# background 


https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin

https://css-tricks.com/almanac/properties/b/background-image/

# border-image

https://developer.mozilla.org/en-US/docs/Web/CSS/border-image

**Comment by xgqfrms-gildata** [comment]
# VS code & emoji bug

![image](https://user-images.githubusercontent.com/29531779/38796314-a541e43a-418d-11e8-8148-56f93050f380.png)

> ok

![image](https://user-images.githubusercontent.com/29531779/38796348-bb40b2f2-418d-11e8-82cd-ca91834d6d54.png)

**Comment by xgqfrms-gildata** [comment]
# svg bug

`https://gist.github.com/b-tiwari/3352eba9d50a08d8d6c712fe8cc73a24#file-app-css`

**Comment by xgqfrms-gildata** [comment]
# Multi-page applications

https://medium.com/a-beginners-guide-for-webpack-2/multi-page-applications-4ae2ebfabc37

**Comment by xgqfrms-gildata** [comment]
# base 64 & import `image` & id


![image](https://user-images.githubusercontent.com/29531779/38802369-d4ad089c-419e-11e8-90b9-2ae4d42dcf33.png)

```html

<figure><img alt="gear_x64.png" title="gear_x64.png" data-uid="test" id="test">
                <figcaption>gear_x64.png 7kb</figcaption>
            </figure>

```

```js

import smallSvgImg from "./imgs/gear_x64.svg";
// let uid = document.querySelector(`[data-uid="test"]`);
let uid = document.querySelector(`#test`);
uid.src = `${smallSvgImg}`;


```

**Comment by xgqfrms-gildata** [comment]
# css class image error

![image](https://user-images.githubusercontent.com/29531779/38803359-8a39f394-41a1-11e8-822e-916eb8f4132d.png)

**Comment by xgqfrms-GitHub** [comment]
https://gist.github.com/xgqfrms-GitHub/

**Comment by xgqfrms-GitHub** [comment]
# Docker

http://www.ruanyifeng.com/blog/2018/02/docker-tutorial.html

http://www.ruanyifeng.com/blog/2018/03/node-debugger.html

**Comment by xgqfrms-gildata** [comment]
# css class name bug

![image](https://user-images.githubusercontent.com/29531779/38842924-4470a9e2-421f-11e8-8548-a5b4e7b66086.png)

**Comment by xgqfrms-gildata** [comment]
# url-loader & true

![image](https://user-images.githubusercontent.com/29531779/38843349-2d69765a-4221-11e8-9fd5-dbc244b8b07f.png)

**Comment by xgqfrms-gildata** [comment]
# shit antd

> global url !== relative local path

![image](https://user-images.githubusercontent.com/29531779/38846796-dd6eb4d4-4230-11e8-898d-72e069745a0f.png)

**Comment by xgqfrms-gildata** [comment]
# holy shit!

![image](https://user-images.githubusercontent.com/29531779/38847028-0b7f2fa6-4232-11e8-97b5-283f48d5d140.png)

```css

@font-face {
  font-family: 'anticon';
  src: url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot');
  /* IE9*/
  src: url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot?#iefix') format('embedded-opentype'),
  /* chrome、firefox */
  url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff') format('woff'),
  /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.ttf') format('truetype'),
  /* iOS 4.1- */
  url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.svg#iconfont') format('svg');
}

```


# it should like this!

```css

@charset "UTF-8";

/* fallback */

@font-face {
    font-family: anticon;
    src: url("../fonts/antd/font_zck90zmlh7hf47vi.eot");
    src: url("../fonts/antd/font_zck90zmlh7hf47vi.eot?#iefix") format("embedded-opentype"), url("../fonts/antd/font_zck90zmlh7hf47vi.woff") format("woff"), url("../fonts/antd/font_zck90zmlh7hf47vi.ttf") format("truetype"), url("../fonts/antd/font_zck90zmlh7hf47vi.svg#iconfont") format("svg")
}

```

**Comment by xgqfrms-gildata** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+author%3Axgqfrms-gildata+is%3Aclosed

**Comment by xgqfrms-gildata** [comment]
# font-awesome npm & font-awesome npm

```sh

$ npm i -S font-awesome

$ npm i -S font-awesome

```

https://www.npmjs.com/package/font-awesome

https://www.npmjs.com/package/font-awesome-webpack
https://stackoverflow.com/questions/48103401/how-to-use-font-awesome-5-installed-via-npm

**Comment by xgqfrms-gildata** [comment]
# JSON 5
> JSON for Humans

https://json5.org/

**Comment by xgqfrms-gildata** [comment]
# tree select js

> checked & data-uid

http://travistidwell.com/jquery.treeselect.js/
https://www.patosai.com/projects/tree-multiselect
https://simonwade.me/jquery-bonsai

https://stackoverflow.com/questions/1232073/tree-like-select-in-html
https://stackoverflow.com/questions/12817715/js-tree-select-node-not-working


https://ourcodeworld.com/articles/read/146/top-5-best-tree-view-jquery-and-javascript-plugins

https://jonmiles.github.io/bootstrap-treeview/
https://www.jstree.com/plugins/

https://mbraak.github.io/jqTree/#demo
https://wwwendt.de/tech/fancytree/demo/#sample-theming.html

**Comment by xgqfrms-gildata** [comment]
# highcharts column max width

>`pointWidth: 20,`

https://stackoverflow.com/questions/5968595/maximum-bar-width-in-highcharts-column-charts

https://stackoverflow.com/questions/5968595/maximum-bar-width-in-highcharts-column-charts/12242307#12242307

> hard coding

```js

    series: [
        {
            type: 'line',
            // type:'spline',
            name: '收益率',
            // color: "#5523cd",
            // color: "#4781b1",
            color: "#f27211",
            data: yields,
            lineWidth: 2,
            zIndex: 3,
            // marker : {
            //     enabled : true,
            //     radius : 0,
            //     symbol: 'square'
            // },
            tooltip: {
                // headerFormat: `
                //     <strong>
                //         {point.x}
                //     </strong>
                //     <br/>
                // `,
                pointFormat: `
                    <span style="color:{point.color}">\u25CF</span>
                    {series.name}: <b>{point.y} %</b><br/>
                `,
                // 点 <span style="color:{point.color}">\u25CF</span> 百分比 :{point.percentage:.0f}%
                // 万元
            },
        },
        {
            type: 'line',
            name: '比较日',
            // color: '#fd0002',
            // color: "#f27211",
            color: "#6ab437",
            data: compare,
            lineWidth: 2,
            zIndex: 2,
            // marker : {
            //     enabled : true,
            //     radius : 0,
            //     symbol: 'square'
            // },
            tooltip: {
                pointFormat: `
                    <span style="color:{point.color}">\u25CF</span>
                    {series.name}: <b>{point.y} %</b><br/>
                `,
            },
        },
        {
            type: 'column',
            yAxis: 1,
            color: "#4781b1",
            pointWidth: 20,
            // color: "#fadc9e",
            // color: "#ff9800",
            // negativeColor: '#7cb5ec',
            // color: "#ff0f2f",
            // negativeColor: "#6ab437",
            name: 'BP差值',
            data: difference,
            zIndex: 1,
            connectNulls: true,// OK
            tooltip: {
                // pointFormat: `
                //     <span style="color:{point.color}">\u25CF</span>
                //     {series.name}: <b><span style="color: #0f0">{point.y}</span> BP</b><br/>
                // `,// ( point.y > 0 ) `color: #0f0` : `color: #f00`;
                pointFormat: `
                    <span style="color:{point.color}">\u25CF</span>
                    {series.name}: <b>{point.y} BP</b><br/>
                `,
            },
        },
    ],


```

**Comment by xgqfrms-gildata** [comment]
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/column-pointwidth-20/

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/column-pointrange/

**Comment by xgqfrms-gildata** [comment]
# radio button

https://stackoverflow.com/questions/4253920/how-do-i-change-the-color-of-radio-buttons

https://developer.mozilla.org/en-US/docs/Web/CSS/:checked

**Comment by xgqfrms-gildata** [comment]
https://webdesign.tutsplus.com/articles/quick-tip-easy-css3-checkboxes-and-radio-buttons--webdesign-8953

https://codepen.io/tutsplus/pen/bgqYJz

**Comment by xgqfrms-gildata** [comment]
# scrollbar & `::webkit`

https://www.processon.com/support#register

![image](https://user-images.githubusercontent.com/29531779/38914480-1e19f458-4312-11e8-81db-04d38fa66cc3.png)


```css

::-webkit-scrollbar {
    width: 12px;
    height: 12px
}

::-webkit-scrollbar-thumb {
    border-width: 2px;
    border-style: solid;
    border-color: #fff;
    border-radius: 6px;
    background-color: #c6c6c6
}

::-webkit-scrollbar-thumb:hover {
    background: #999
}

```
