### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by xgqfrms** [gildata/RAIO#334]
# CSS Modules

https://github.com/css-modules/css-modules

https://css-tricks.com/css-modules-part-1-need/

***

https://www.cnblogs.com/xgqfrms/p/9139346.html

**Comment by xgqfrms** [comment]
# BEM

https://en.bem.info/methodology/

https://css-tricks.com/bem-101/

**Comment by xgqfrms** [comment]
# ES6

https://css-tricks.com/lets-learn-es2015/

https://www.youtube.com/playlist?list=PL57atfCFqj2h5fpdZD-doGEIs0NZxeJTX

**Comment by xgqfrms** [comment]
# es6 module loader

https://www.jvandemo.com/a-10-minute-primer-to-javascript-modules-module-formats-module-loaders-and-module-bundlers/

https://addyosmani.com/writing-modular-js/

https://stackoverflow.com/questions/40298304/do-i-still-need-a-module-loader-if-im-using-es6-modules

**Comment by xgqfrms** [comment]
# css auto prefixer

https://autoprefixer.github.io

https://marketplace.visualstudio.com/items?itemName=sporiley.css-auto-prefix

**Comment by xgqfrms** [comment]
# vs code & css auto prefix

```json

{
    "window.zoomLevel": 0,
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "jspm_packages": true,
        "node_modules": true,
        "**/.zip": true,
        "**/.sh": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true
    },
    "editor.formatOnSave": false,
    "editor.renderWhitespace": "all",
    "editor.fontSize": 16,
    "editor.tabSize": 4,
    "editor.multiCursorModifier": "alt",
    "editor.wordWrap": "on",
    "editor.insertSpaces": true,
    "files.encoding": "utf8",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "[typescript]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },
    "[markdown]": {
        "editor.formatOnSave": true,
        "editor.renderWhitespace": "all",
        "editor.acceptSuggestionOnEnter": "off"
    },
    "files.associations": {
        "*.jsx": "javascriptreact",
        "*.js": "javascriptreact"
    },
    "editor.snippetSuggestions": "top",
    "jsDocCompletion.enabled": true,
    // When enabled, typing /** triggers documentation automatically.
    "docthis.automaticForBlockComments": true,
    // When enabled, type information is added to comment tags.
    "docthis.includeTypes": true,
    // When enabled, memberOf information is added to comment tags on class members.
    "docthis.includeMemberOfOnClassMembers": true,
    // When enabled, memberOf information is added to comment tags on interface members.
    "docthis.includeMemberOfOnInterfaceMembers": true,
    // When enabled, JSDoc comments for functions and methods will include @description.
    "docthis.includeDescriptionTag": true,
    // When enabled, hungarian notation will be used as a type hint.
    "docthis.enableHungarianNotationEvaluation": true,
    // When enabled, will use names of params & methods as type hints.
    "docthis.inferTypesFromNames": true,
    // When enabled, will add the @author tag.
    "docthis.includeAuthorTag": true,
    // When docthis.includeAuthorTag is enabled, will add @author tag with this value.
    "docthis.authorName": "xgqfrms",
    // HTML
    "html.format.extraLiners": "/html",
    "html.format.enable": false,
    "html.format.contentUnformatted": "body, div, section, script, pre,code,textarea",
    "explorer.confirmDragAndDrop": false,
    "git.ignoreMissingGitWarning": true,
    "explorer.confirmDelete": false,
    // The list of attributes to add support for, and what prefixes each one should receive.
    "css-auto-prefix.prefixes": {
        "transform": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "transition": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "border-radius": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "animation": [
            "webkit"
        ],
        "box-reflect": [
            "webkit"
        ],
        "filter": [
            "webkit"
        ],
        "font-feature-settings": [
            "webkit",
            "moz"
        ],
        "backface-visibility": [
            "webkit"
        ],
        "box-decoration-break": [
            "webkit"
        ],
        "hyphens": [
            "webkit",
            "moz",
            "ms"
        ],
        "marquee-direction": [
            "webkit"
        ],
        "marquee-play-count": [
            "webkit"
        ],
        "marquee-speed": [
            "webkit"
        ],
        "marquee-style": [
            "webkit"
        ],
        "text-combine-upright": [
            "webkit",
            "moz",
            "ms"
        ],
        "text-decoration-color": [
            "moz"
        ],
        "text-decoration-line": [
            "moz"
        ],
        "text-decoration-style": [
            "moz"
        ],
        "text-orientation": [
            "webkit"
        ],
        "writing-mode": [
            "webkit",
            "ms"
        ]
    }
}

```

**Comment by xgqfrms** [comment]
# which css attributes needs prefixes?

http://shouldiprefix.com/#box-sizing

https://caniuse.com/#search=box-sizing

https://developer.mozilla.org/en-US/

https://www.sitepoint.com/vendor-specific-properties/

https://stackoverflow.com/questions/5411026/list-of-css-vendor-prefixes

https://www.w3schools.com/cssref/css3_browsersupport.asp


***

https://www.w3schools.com/cssref/css3_browsersupport.asp

https://bitsofco.de/css-vendor-prefixes/

https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

**Comment by xgqfrms** [comment]
# `ext-overflow: ellipsis` & `display: -webkit-box;`

> 多行文本溢出显示省略号(…) text-overflow: ellipsis

https://github.com/gildata/RAIO/issues/213

```css

.fv-important-infos-table-tbody>tr:nth-of-type(1)>td:last-child, .fv-important-infos-table-tbody>tr:nth-of-type(2)>td:last-child {
    background: #25292e;
    overflow: hidden;
    word-wrap: break-word;
    text-overflow: ellipsis;
    /* white-space: nowrap; */
    /* width: 400px; */
    /* height: calc(23px * 3); */
    box-sizing: border-box;
    /* height: 63px !important; */
    /* height: 77px !important; */
    line-height: 21px !important;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    /* font-size: 13px; */
    /* padding-top: 7px; */
    /* padding-bottom: 7px; */
    /* margin-top: 7px; */
    /* margin-bottom: 7px; */
    /* padding: 0; */
    padding-top: 4px;
    padding-bottom: 4px;
    /* position: relative; */
    border: 0;
    /* border-bottom: 1px solid #e9e9e9; */
}


```

**Comment by xgqfrms** [comment]
# OK

```css


.fixed-width {
    line-height: 36px;
    width: 610px;
    overflow: hidden;
    text-overflow: ellipsis;
    word-wrap: break-word;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
}

```

![image](https://user-images.githubusercontent.com/18028768/40962305-bfbe241a-68d7-11e8-86ca-8bfa192247fe.png)

**Comment by xgqfrms** [comment]
```css

.fv-top-ten-shareholders-table-tbody>tr[data-value="fv-top-ten-shareholders-table-tr"]>td:nth-of-type(2) {
    text-align: left;
    /* min-width: 535px; */
    max-width: 200px;
    text-overflow: ellipsis;
    overflow: hidden;
    /* word-break: break-all; */
    white-space: nowrap;
}

```

**Comment by xgqfrms** [comment]
# VS Code Configs Alll in One & settings.json & launch.json & tasks.json


## settings.json

```json

// 将设置放入此文件中以覆盖默认设置
{
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "**/jspm_packages": true,
        "**/node_modules": true,
        "**/.zip": true,
        "**/.sh": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true
    },
    "editor.formatOnSave": false,
    "editor.formatOnPaste": true,
    "editor.renderWhitespace": "all",
    "editor.fontSize": 16,
    "editor.tabSize": 4,
    "editor.multiCursorModifier": "alt",
    "editor.wordWrap": "on",
    "editor.insertSpaces": true,
    "files.encoding": "utf8",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "[typescript]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },
    "[markdown]": {
        "editor.formatOnSave": true,
        "editor.renderWhitespace": "all",
        "editor.acceptSuggestionOnEnter": "off"
    },
    "files.associations": {
        "*.jsx": "javascriptreact",
        "*.js": "javascriptreact"
    },
    "editor.snippetSuggestions": "top",
    // When enabled, typing /** triggers documentation automatically.
    "docthis.automaticForBlockComments": true,
    // When enabled, type information is added to comment tags.
    "docthis.includeTypes": true,
    // When enabled, memberOf information is added to comment tags on class members.
    "docthis.includeMemberOfOnClassMembers": true,
    // When enabled, memberOf information is added to comment tags on interface members.
    "docthis.includeMemberOfOnInterfaceMembers": true,
    // When enabled, JSDoc comments for functions and methods will include @description.
    "docthis.includeDescriptionTag": true,
    // When enabled, hungarian notation will be used as a type hint.
    "docthis.enableHungarianNotationEvaluation": true,
    // When enabled, will use names of params & methods as type hints.
    "docthis.inferTypesFromNames": true,
    // When enabled, will add the @author tag.
    "docthis.includeAuthorTag": true,
    // When docthis.includeAuthorTag is enabled, will add @author tag with this value.
    "docthis.authorName": "xgqfrms",
    // HTML & overwrite User settings.json
    "html.format.extraLiners": "",
    "html.format.enable": false,
    "html.format.contentUnformatted": "body, div, section, script, pre,code,textarea"
}


```

> new version

```json

// 将设置放入此文件中以覆盖默认设置
{
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "**/jspm_packages": true,
        "**/node_modules": true,
        "**/.zip": true,
        "**/.sh": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true
    },
    "editor.formatOnSave": true,
    "editor.formatOnPaste": false,
    "editor.renderWhitespace": "all",
    "editor.fontSize": 16,
    "editor.tabSize": 4,
    "editor.multiCursorModifier": "alt",
    "editor.wordWrap": "on",
    "editor.insertSpaces": true,
    "files.encoding": "utf8",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "[typescript]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    },
    "[markdown]": {
        "editor.formatOnSave": true,
        "editor.renderWhitespace": "all",
        "editor.acceptSuggestionOnEnter": "off"
    },
    "files.associations": {
        "*.jsx": "javascriptreact",
        "*.js": "javascriptreact"
    },
    "editor.snippetSuggestions": "top",
    // When enabled, typing /** triggers documentation automatically.
    "docthis.automaticForBlockComments": true,
    // When enabled, type information is added to comment tags.
    "docthis.includeTypes": true,
    // When enabled, memberOf information is added to comment tags on class members.
    "docthis.includeMemberOfOnClassMembers": true,
    // When enabled, memberOf information is added to comment tags on interface members.
    "docthis.includeMemberOfOnInterfaceMembers": true,
    // When enabled, JSDoc comments for functions and methods will include @description.
    "docthis.includeDescriptionTag": true,
    // When enabled, hungarian notation will be used as a type hint.
    "docthis.enableHungarianNotationEvaluation": true,
    // When enabled, will use names of params & methods as type hints.
    "docthis.inferTypesFromNames": true,
    // When enabled, will add the @author tag.
    "docthis.includeAuthorTag": true,
    // When docthis.includeAuthorTag is enabled, will add @author tag with this value.
    "docthis.authorName": "xgqfrms",
    // HTML & overwrite User settings.json
    "html.format.extraLiners": "",
    "html.format.enable": false,
    "html.format.contentUnformatted": "body, div, section, script, pre,code,textarea",
    "npm.enableScriptExplorer": true,
    // The list of attributes to add support for, and what prefixes each one should receive.
    "css-auto-prefix.prefixes": {
        "transform": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "transition": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "border-radius": [
            "webkit",
            "moz",
            "ms",
            "o"
        ],
        "animation": [
            "webkit"
        ],
        "box-reflect": [
            "webkit"
        ],
        "filter": [
            "webkit"
        ],
        "font-feature-settings": [
            "webkit",
            "moz"
        ],
        "backface-visibility": [
            "webkit"
        ],
        "box-decoration-break": [
            "webkit"
        ],
        "hyphens": [
            "webkit",
            "moz",
            "ms"
        ],
        "marquee-direction": [
            "webkit"
        ],
        "marquee-play-count": [
            "webkit"
        ],
        "marquee-speed": [
            "webkit"
        ],
        "marquee-style": [
            "webkit"
        ],
        "text-combine-upright": [
            "webkit",
            "moz",
            "ms"
        ],
        "text-decoration-color": [
            "moz"
        ],
        "text-decoration-line": [
            "moz"
        ],
        "text-decoration-style": [
            "moz"
        ],
        "text-orientation": [
            "webkit"
        ],
        "writing-mode": [
            "webkit",
            "ms"
        ]
    }
}



```


## tasks.json


```json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "app",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "dev",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "prod",
            "problemMatcher": []
        }
    ]
}


```


## launch.json


```json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "app",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "dev",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "prod",
            "problemMatcher": []
        }
    ]
}



```



***

**Comment by xgqfrms** [comment]
# 橘子 !== 桔子 ? 橘子 : 桔子

**Comment by xgqfrms** [comment]
# 橘子 !== 桔子 ? 橘子 : 桔子

![image](https://user-images.githubusercontent.com/7291672/41017228-9541980c-6986-11e8-8b3e-c7e2ba217c6f.png)

**Comment by xgqfrms** [comment]
# bug

> not ignore folders

![image](https://user-images.githubusercontent.com/7291672/41018812-500943fe-698e-11e8-9529-b42e87f88032.png)

![image](https://user-images.githubusercontent.com/7291672/41018832-6f770366-698e-11e8-9254-11d0ccc55b4d.png)

**Comment by xgqfrms** [comment]
# bad

![image](https://user-images.githubusercontent.com/7291672/41019742-99ac8378-6992-11e8-870e-d9c03ddf7092.png)

![image](https://user-images.githubusercontent.com/7291672/41019754-a9d80218-6992-11e8-87d9-02bea2c38688.png)

**Comment by xgqfrms** [comment]
# shit dell touchpad

> windows 10 update

![image](https://user-images.githubusercontent.com/7291672/41023469-1ea18d38-699f-11e8-9f44-7172e27c73b1.png)

![image](https://user-images.githubusercontent.com/7291672/41023470-1ea5b62e-699f-11e8-85a0-73c28f74fabd.png)

https://support.microsoft.com/zh-cn/help/4027871/windows-10-touchpad-gestures

**Comment by xgqfrms** [comment]
#  front end & back end

https://en.wikipedia.org/wiki/Server-side

https://en.wikipedia.org/wiki/Front_and_back_ends

**Comment by xgqfrms** [comment]
# MutationObserver API

https://davidwalsh.name/mutationobserver-api


```js



```

**Comment by xgqfrms** [comment]
https://www.upwork.com/hiring/development/beginners-guide-to-front-end-development/

![ms-kb-bug](https://user-images.githubusercontent.com/7291672/41074153-39bba140-6a39-11e8-9646-42d8e8a4a7d0.gif)

**Comment by xgqfrms** [comment]
# link to card

> how to create a card with a url link in js?

![image](https://user-images.githubusercontent.com/7291672/41075072-8db3a546-6a3d-11e8-83a8-3a544d978a58.png)


https://docs.embed.ly/docs/cards

https://medium.freecodecamp.org/creating-a-bare-bones-quote-generator-with-javascript-and-html-for-absolute-beginners-5264e1725f08

**Comment by xgqfrms** [comment]
# card api

![image](https://user-images.githubusercontent.com/7291672/41075278-86a33842-6a3e-11e8-9342-720359b71696.png)


![image](https://user-images.githubusercontent.com/7291672/41075301-9c23ee28-6a3e-11e8-8555-ce2b9469ba97.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/41075501-77f17c5e-6a3f-11e8-9c2e-e019e333543f.png)

![image](https://user-images.githubusercontent.com/7291672/41075517-84c9a46a-6a3f-11e8-92f7-0c2c34715353.png)

![image](https://user-images.githubusercontent.com/7291672/41075521-8dc7c218-6a3f-11e8-992f-5bbf1a32abc0.png)

![image](https://user-images.githubusercontent.com/7291672/41075540-a210edf8-6a3f-11e8-9f44-80594cac2a02.png)


![image](https://user-images.githubusercontent.com/7291672/41075587-dcefad60-6a3f-11e8-9e08-3812ebd3067e.png)


![image](https://user-images.githubusercontent.com/7291672/41075605-fec3a61c-6a3f-11e8-89b4-d8f05150fae6.png)



```html

<blockquote class="embedly-card" data-card-key="2f7f4c74547f467796238b661b1ef496" data-card-type="article-full"><h4><a href="https://www.xgqfrms.xyz">xgqfrms™, xgqfrms® : xgqfrms's offical website of GitHub!</a></h4><p>xgqfrms.xyz : xgqfrms's offical website of GitHub! & xgqfrms, webgeeker, github, xgqfrms.xyz, webgeeker.xyz, Tutorials, ES5 ES6 ES7, React 2, Angular 2, Ionic 2</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>


```

**Comment by xgqfrms** [comment]
# backend

![image](https://user-images.githubusercontent.com/7291672/41075762-b907bac2-6a40-11e8-8948-aa09ed9b5dfa.png)


```html

<!DOCTYPE html>
<html lang="zh-Hans">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="xgqfrms">
    <meta name="generator" content="VS code">
    <title>Link Crads</title>
</head>

<body>
    <section>
        <h1>Link Crads</h1>
        <a href="https://app.embed.ly/organization/cards-1/embed/https%3A%2F%2Fwww.xgqfrms.xyz">https://app.embed.ly/organization/cards-1/embed/https%3A%2F%2Fwww.xgqfrms.xyz</a>
    </section>
    <section>
        <blockquote class="embedly-card" data-card-key="2f7f4c74547f467796238b661b1ef496" data-card-type="article-full">
            <h4>
                <a href="https://www.xgqfrms.xyz">xgqfrms™, xgqfrms® : xgqfrms's offical website of GitHub!</a>
            </h4>
            <p>
                xgqfrms.xyz : xgqfrms's offical website of GitHub! & xgqfrms, webgeeker, github, xgqfrms.xyz, webgeeker.xyz, Tutorials, ES5 ES6 ES7, React 2, Angular 2, Ionic 2
            </p>
        </blockquote>
        <script async src="https://cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
    </section>
</body>

</html>

```

https://i-cdn.embed.ly/1/display?height=16&key=fd92ebbc52fc43fb98f69e50e7893c13&url=https%3A%2F%2Fwww.xgqfrms.xyz%2Ffavicon-16x16.png&width=16

![image](https://user-images.githubusercontent.com/7291672/41075794-d642929c-6a40-11e8-8062-aabedbdd06ee.png)

https://api-cdn.embed.ly/1/card-details?card=1&key=2f7f4c74547f467796238b661b1ef496&native=true&scheme=https&urls=https%3A%2F%2Fwww.xgqfrms.xyz&v=MTcyMDEw&youtube_showinfo=0


```json

[
    {
        "provider_url": "https://www.xgqfrms.xyz",
        "description": "xgqfrms.xyz : xgqfrms's offical website of GitHub! & xgqfrms, webgeeker, github, xgqfrms.xyz, webgeeker.xyz, Tutorials, ES5 ES6 ES7, React 2, Angular 2, Ionic 2",
        "embeds": [
            
        ],
        "safe": true,
        "provider_display": "www.xgqfrms.xyz",
        "related": [
            
        ],
        "favicon_url": "https://www.xgqfrms.xyz/favicon-16x16.png",
        "authors": [
            
        ],
        "images": [
            
        ],
        "cache_age": 86399,
        "card": {
            "paid": false
        },
        "language": "en",
        "app_links": [
            
        ],
        "original_url": "https://www.xgqfrms.xyz",
        "url": "https://www.xgqfrms.xyz",
        "media": {
            
        },
        "title": "xgqfrms™, xgqfrms® : xgqfrms's offical website of GitHub!",
        "offset": null,
        "lead": null,
        "content": false,
        "entities": [
            
        ],
        "favicon_colors": [
            {
                "color": [
                    40,
                    44,
                    43
                ],
                "weight": 0.015625
            },
            {
                "color": [
                    156,
                    192,
                    56
                ],
                "weight": 0.014892578100000001
            },
            {
                "color": [
                    240,
                    242,
                    227
                ],
                "weight": 0.0134277344
            },
            {
                "color": [
                    92,
                    113,
                    36
                ],
                "weight": 0.0068359375
            },
            {
                "color": [
                    168,
                    151,
                    131
                ],
                "weight": 0.0048828125
            }
        ],
        "keywords": [
            
        ],
        "published": null,
        "provider_name": "Xgqfrms",
        "type": "html"
    }
]

```

**Comment by xgqfrms** [comment]
# Embedly

> The most effective platform on the web to engage your audience through `rich media embeds`. Get features like images, video, polls, slideshows, music, live video, forms, gifs, infographics and more automatically.


https://github.com/embedly

https://github.com/embedly/player.js

https://docs.embed.ly/docs/cards
https://docs.embed.ly/v1.0/docs/platformjs

**Comment by xgqfrms** [comment]
http://playerjs.io

https://codepen.io/xgqfrms/full/ZRpLZv/

**Comment by xgqfrms** [comment]
# css name

![image](https://user-images.githubusercontent.com/7291672/41136090-484f8b08-6b07-11e8-9878-61b37fd717d0.png)

```js
    {
        test: /\.((s*)css|sass)$/,
        // test: /\.(css|scss|sass)$/,
        use: ExtractTextPlugin.extract({
            use: [
                {
                    loader: "css-loader",
                    options: {
                        url: false,
                        // url: true,
                        minimize: true,
                        sourceMap: true,
                        modules: true,
                        importLoaders: 1,
                        // localIdentName: "[local]",
                        localIdentName: "f10_[name]_[local]",
                        // localIdentName: "[path][name]__[local]",
                        // localIdentName: "[name]__[local]___[hash:base64:8]",
                    }
                },
                {
                    loader: "sass-loader",
                    options: {
                        sourceMap: true,
                    }
                }
            ],
            fallback: "style-loader",
            // allChunks: true,
            // publicPath: "./public",// not work ant all
        }),
    },
```
> latest-news.css

```css
@charset "UTf-8";

/* latest-news.css */

:root {
    --cololr: #000;
    --default-cololr: #fff;
    --new-cololr: #0f0;
}

body {
    font-family: "Microsoft YaHei", sans-serif;
    font-size: 12px;
}

*,
html {
    box-sizing: border-box;
}

::before,
::after {
    margin: 0;
    padding: 0;
}

.table {
    box-sizing: border-box;
    font-size: 13px;
    color: #121212;
    background: #fff;
    width: calc(100% - 10px);
    margin: 5px;
    border-collapse: collapse;
    border-spacing: 0;
    min-width: 1024px;
}

.table td {
    /* line-height: 36px; */
    height: 36px;
    padding: 0 5px;
    border: 1px solid #d7dbe0;
    color: #777374;
    font-weight: normal;
    text-align: left;
}

span {
    display: inline-block;
    /* vertical-align: middle; */
    /* background: #f0f; */
}

.fixed-width,
.fixed-min-width,
.fixed-max-width {
    line-height: 36px;
    height: 36px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    background: #0f0f;
    color: #121212;
    /* margin-bottom: -13px; */
    padding: 0 3px;
    vertical-align: middle;
}

.fixed-width {
    /* width: 67vw; */
    width: 700px;
}

.fixed-min-width {
    /* width: 17vw; */
    width: 183px;
}

.fixed-max-width {
    width: 953px;
}

.title-box {
    width: calc(100% - 10px);
    margin: 5px;
    min-width: 1024px;
    background: #f1f1f1;
    border: 1px solid #e1e1e1;
}

.title-icons {
    position: relative;
    color: #4d4d4d;
    text-indent: 14px;
    margin-left: 0;
    font-weight: 600;
    font-size: 15px;
    margin-top: 6px;
    margin-bottom: 6px;
}

.title-icons::before {
    position: absolute;
    top: 3px;
    left: 5px;
    content: "";
    display: inline-block;
    width: 4px;
    background: #f79530;
    height: 15px;
}

@media all and (min-width: 1400px) {
    .fixed-width {
        /* width: 67vw; */
        width: 1000px;
    }
    .fixed-min-width {
        /* width: 17vw; */
        width: 203px;
    }
    .fixed-max-width {
        width: 1303px;
    }
    .table {
        min-width: 1366px;
    }
    .title-box {
        min-width: 1366px;
    }
}

```
> latest-news.min.css

```css
:root{--cololr:#000;--default-cololr:#fff;--new-cololr:#0f0}body{font-family:Microsoft YaHei,sans-serif;font-size:12px}*,html{box-sizing:border-box}:after,:before{margin:0;padding:0}.f10_latest-news_table{box-sizing:border-box;font-size:13px;color:#121212;background:#fff;width:calc(100% - 10px);margin:5px;border-collapse:collapse;border-spacing:0;min-width:1024px}.f10_latest-news_table td{height:36px;padding:0 5px;border:1px solid #d7dbe0;color:#777374;font-weight:400;text-align:left}span{display:inline-block}.f10_latest-news_fixed-max-width,.f10_latest-news_fixed-min-width,.f10_latest-news_fixed-width{line-height:36px;height:36px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;background:#0f0f;color:#121212;padding:0 3px;vertical-align:middle}.f10_latest-news_fixed-width{width:700px}.f10_latest-news_fixed-min-width{width:183px}.f10_latest-news_fixed-max-width{width:953px}.f10_latest-news_title-box{width:calc(100% - 10px);margin:5px;min-width:1024px;background:#f1f1f1;border:1px solid #e1e1e1}.f10_latest-news_title-icons{position:relative;color:#4d4d4d;text-indent:14px;margin-left:0;font-weight:600;font-size:15px;margin-top:6px;margin-bottom:6px}.f10_latest-news_title-icons:before{position:absolute;top:3px;left:5px;content:"";display:inline-block;width:4px;background:#f79530;height:15px}@media (min-width:1400px){.f10_latest-news_fixed-width{width:1000px}.f10_latest-news_fixed-min-width{width:203px}.f10_latest-news_fixed-max-width{width:1303px}.f10_latest-news_table,.f10_latest-news_title-box{min-width:1366px}}
/*# sourceMappingURL=latest-news.min.css.map?7356c9de*/

```
