### ISSUE TITLE
vue & components name bug

### ISSUE THREAD

**Issue by xgqfrms** [gildata/RAIO#364]
# vue & components name bug

https://codepen.io/webgeeker/pen/KBVeee

```html

<!DOCTYPE html>
<html lang="zh-Hans">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="xgqfrms">
    <meta name="generator" content="VS code">
    <title>Vue bug & &lt;Xyz&gt;&lt;/Xyz&gt; !== &lt;XYZ&gt;&lt;/XYZ&gt;
    </title>
    <script src="https://cdn.bootcss.com/vue/2.2.2/vue.min.js"></script>
</head>

<body>
    <section>
        <!-- 全局组件 -->
        <div id="test">
            <Abc></Abc>
        </div>
        <!-- 局部组件 -->
        <div id="app">
            <Xyz></Xyz>
        </div>
    </section>
    <!-- js -->
    <script>
        // 注册
        Vue.component('Abc', {
            // template: '<div title="need box wrap template"><h1>全局组件 & 自定义组件!</h1><p>所有实例都能用全局组件。</p></div>',
            // support `ES6 template string`
            template: `
                <div title="need box wrap template">
                    <h1>全局组件 & 自定义组件!</h1>
                    <p>所有实例都能用全局组件。</p>
                </div>
            `,
        });
        // 创建根实例
        new Vue({
            el: '#test'
        });
    </script>
    <script>
        let local_component = {
            template: `
                <div title="need box wrap template">
                    <h1>局部组件 & 自定义组件!</h1>
                    <p>局部组件只能在该实例中使用。</p>
                </div>
            `,
        };
        // 创建根实例
        new Vue({
            el: '#app',
            components: {
                // <Xyz> 将只在父模板可用
                'Xyz': local_component
            }
        });
    </script>
</body>

</html>

```

**Comment by xgqfrms** [comment]
https://codesandbox.io/s/m5wq94580j

**Comment by xgqfrms** [comment]
# sketchpad

https://sketch.io/sketchpad/index.html

**Comment by xgqfrms** [comment]
# bug

> `https://github.com/sentsin/layui/issues/297`

**Comment by xgqfrms** [comment]
# setDragImage

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer#setDragImage

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage

**Comment by xgqfrms** [comment]
# 03-drag-with-created-a-visible-node

https://codepen.io/xgqfrms/pen/qyZxJe

**Comment by xgqfrms** [comment]
https://kryogenix.org/code/browser/

**Comment by xgqfrms** [comment]
# Tableau

> 可视化图表

https://cn.udacity.com/course/business-analyst-nanodegree--nd100-cn

https://www.tableau.com/

**Comment by xgqfrms** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild

https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove


***


https://www.w3schools.com/js/js_htmldom_nodes.asp

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/42794635-7377c9b6-89b2-11e8-8099-9d373e6a5c97.png)

https://kryogenix.org/code/browser/jses/

https://codepen.io/xgqfrms/pen/pZyLbQ

**Comment by xgqfrms** [comment]
# HTML5 & DnD & image shortcuts

https://codepen.io/webgeeker/pen/jpqezG

**Comment by xgqfrms** [comment]
#  preload image

```js

// preload image
 (new Image()).src="http://kryogenix.org/images/hackergotchi-simpler.png";

```

https://kryogenix.org/code/browser/custom-drag-image.html

**Comment by xgqfrms** [comment]
https://codepen.io/webgeeker/full/KBzrxE/

**Comment by xgqfrms** [comment]
# `[].forEach.call(cols)` & `let btns = [...document.querySelectorAll(`[data-btn*="btn"]`)];`

https://www.html5rocks.com/en/tutorials/dnd/basics/


```js

var cols = document.querySelectorAll('#columns .column');
[].forEach.call(cols, function(col) {
  col.addEventListener('dragstart', handleDragStart, false);
  col.addEventListener('dragenter', handleDragEnter, false);
  col.addEventListener('dragover', handleDragOver, false);
  col.addEventListener('dragleave', handleDragLeave, false);
});

let btns = [...document.querySelectorAll(`[data-btn*="btn"]`)];

```

**Comment by xgqfrms** [comment]
https://html.spec.whatwg.org/multipage/dnd.html#the-datatransfer-interface

**Comment by xgqfrms** [comment]
# addEvent

view-source:https://html5demos.com/drag/

![image](https://user-images.githubusercontent.com/7291672/42813286-0d152542-89f3-11e8-8dd7-81cccd33f0ad.png)

**Comment by xgqfrms** [comment]
# `user-select: none;` & `[draggable="true"]

> `[draggable="true"]` === `[draggable]`

```css

    /* Prevent the contents of draggable elements from being selectable. */
    
    [draggable] {
        -moz-user-select: none;
        -khtml-user-select: none;
        -webkit-user-select: none;
        user-select: none;
        /* Required to make elements draggable in old WebKit */
        -khtml-user-drag: element;
        -webkit-user-drag: element;
    }
    
    [draggable="true"] {
        -moz-user-select: none;
        -khtml-user-select: none;
        -webkit-user-select: none;
        user-select: none;
        /* Required to make elements draggable in old WebKit */
        -khtml-user-drag: element;
        -webkit-user-drag: element;
    }

```
