### ISSUE TITLE
ES6 Map & WeakMap & ES6 Set & WeakSet

### ISSUE THREAD

**Issue by xgqfrms** [gildata/RAIO#365]
# ES6 Map & WeakMap

# ES6 Set & WeakSet

**Comment by xgqfrms** [comment]
# autocomplete & off

> `<input autocomplete="on|off">`

https://www.w3schools.com/tags/att_input_autocomplete.asp

**Comment by xgqfrms** [comment]
# preload & erase canvas

https://createjs.com/demos/easeljs/alphamaskreveal

https://createjs.com/easeljs

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/42929102-a848ffb0-8b6b-11e8-8fb0-3b7d55268705.png)


```html

<link rel="prefetch" href="//example.com/next-page.html" as="html" crossorigin="use-credentials">
<link rel="prefetch" href="/library.js" as="script">

```
https://www.w3.org/TR/resource-hints/#dfn-prefetch

**Comment by xgqfrms** [comment]
http://www.zhangxinxu.com/wordpress/2011/02/html5-drag-drop-%E6%8B%96%E6%8B%BD%E4%B8%8E%E6%8B%96%E6%94%BE%E7%AE%80%E4%BB%8B/

http://www.zhangxinxu.com/study/201102/html5-drag-and-drop.html

**Comment by xgqfrms** [comment]
https://github.com/gildata/RAIO/issues/236

**Comment by xgqfrms** [comment]
https://github.com/xgqfrms/HTML5

**Comment by xgqfrms** [comment]
https://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger


![image](https://user-images.githubusercontent.com/7291672/42943093-71cbe802-8b94-11e8-84f3-90c0820d24eb.png)

**Comment by xgqfrms** [comment]
# keyghost & table


https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing
https://stackoverflow.com/questions/339923/set-cellpadding-and-cellspacing-in-css
https://www.w3schools.com/csSref/pr_border-spacing.asp

## cellpadding & cellspacing

````css

table[data-style="keyghost-table"] {
    font-weight: normal;
    margin-top: 2px;
    margin-left: -1px;
    width: 100%;
    height: auto;
    font-size: 12px;
    color: #4d4d4d;
    text-align: center;
    z-index: 9999;
    background: #eee;
    overflow-y: auto;
    border-spacing: 0;
    border-collapse: collapse;
}


/*

<table cellspacing="1" cellpadding="1">

https://stackoverflow.com/questions/339923/set-cellpadding-and-cellspacing-in-css


cellpadding === td padding


cellspacing === table border-spacing & table border-collapse

*/

```
