### ISSUE TITLE
Fixe Head & Scroll Content

### ISSUE THREAD

**Issue by xgqfrms** [gildata/RAIO#366]
# Fixe Head & Scroll Content

> css layout

**Comment by xgqfrms** [comment]
# CSS table-layout  & fixed

> The `table-layout` property defines the `algorithm` used to lay out table cells, rows, and columns.

```css

table.a {
    table-layout: auto;
    width: 180px; 
}

table.b {
    table-layout: fixed;
    width: 180px; 
}

```

https://www.w3schools.com/cssref/pr_tab_table-layout.asp

https://www.w3schools.com/cssref/tryit.asp?filename=trycss_table_table-layout
