### ISSUE TITLE
scrollbar css

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#42]
# scrollbar css

> Customize the Browser's Scrollbar with CSS

https://scotch.io/tutorials/customize-the-browsers-scrollbar-with-css

```css


```

> scrollbar

https://css-tricks.com/almanac/properties/s/scrollbar/

https://css-tricks.com/examples/WebKitScrollbars/

https://stackoverflow.com/questions/9251354/css-customized-scroll-bar-in-div

**Comment by xgqfrms-gildata** [comment]
https://codepen.io/akinjide/pen/BpggrZ

**Comment by xgqfrms-gildata** [comment]
# pug to html converter

https://codepen.io/gildata/pen/dzGaeY?editors=1100

> Convert Jade to HTML

https://www.browserling.com/tools/jade-to-html

```jade/pug
- var n = 1

h1 Customize the Browser's Scrollbar with CSS

#wrapper
  .scrollbar#style-default
    .force-overflow
   
while n < 12
  .scrollbar(id="style-" + n++)
    .force-overflow
```

```html
<h1>Customize the Browser's Scrollbar with CSS</h1>
<div id="wrapper">
  <div class="scrollbar" id="style-default">
    <div class="force-overflow"></div>
  </div>
</div>
<div class="scrollbar" id="style-1">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-2">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-3">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-4">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-5">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-6">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-7">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-8">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-9">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-10">
  <div class="force-overflow"></div>
</div>
<div class="scrollbar" id="style-11">
  <div class="force-overflow"></div>
</div>
```


> html 2 jade

http://html2jade.org/

**Comment by xgqfrms-gildata** [comment]
#`box-sizing: border-box;`

> border-box: width 和 height 属性包括内容，内边距和边框，但不包括 <del>`外边距`</del>。

https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Styling_boxes/Box_model_recap

**Comment by xgqfrms-gildata** [comment]
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>layout</title>
    <style>
        html,
        body,
        div {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        
        .app-container {
            position: relative;
            box-sizing: border-box;
            width: 100%;
            height: 100%;
            /* overflow: hidden; */
        }
        
        .app-sider {
            box-sizing: border-box;
            background: #000;
            width: 200px;
            height: 100vh;
            /* position: absolute; */
            position: fixed;
            top: 0;
            left: 0;
            color: #fff;
        }
        
        .app-body {
            background: #777;
            border: 1px solid #f00;
            box-sizing: border-box;
            height: 100%;
            width: calc(100%-200px);
            margin-left: 200px;
        }
        
        .app-header {
            box-sizing: border-box;
            background: #0f0;
            width: 100%;
            height: 100px;
        }
        
        .app-content {
            background: rgba(255, 255, 255, 0.5);
            color: #000;
            box-sizing: border-box;
            width: 100%;
            padding: 10px;
            /* margin: 5px; */
            /* overflow: visible; */
            /* border-box: width 和 height 属性包括内容，内边距和边框，但不包括 外边距。  */
        }
        
        .app-footer {
            box-sizing: border-box;
            width: 100%;
            height: 50px;
            background: rgba(255, 0, 255, 0.5);
        }
        /* scrollbar */
        
        body {
            /* overflow: hidden; */
        }
        
        body::-webkit-scrollbar {
            width: 8px;
            /* scrollbar width */
        }
        
        body::-webkit-scrollbar-thumb {
            border-radius: 10px;
            height: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
            box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
            background-color: #555;
        }
        
        body::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
            box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
            border-radius: 10px;
            background-color: #F5F5F5;
        }
    </style>
</head>
<!-- app\layout.html -->

<body>
    <div class="app-container">
        <div class="app-sider">
            sider
        </div>
        <div class="app-body">
            <header class="app-header">
                header
            </header>
            <div class="app-content">
                content xxx
                <br> xxx
                <br> xxxcontent xxx content xxx content xxx content xxx content xxx content xxx content xxx content xxx content xxxcontent xxx content xxx content xxx content xxx content xxx content xxx content xxx content xxx
                <br> xxx
                <br> xxx
                <br> xxx

                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx

                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx

                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br> xxx
                <br>
            </div>
            <footer class="app-footer">
                footer
            </footer>
        </div>
    </div>
</body>

</html>
```

**Comment by xgqfrms-gildata** [comment]
# scrollbar height,

> scrollbar height, it will auto changed by the content height!

```css
        body::-webkit-scrollbar {
            width: 8px;
            /* scrollbar width */
        }
        /* scrollbar height, auto change by the content height */
        
        body::-webkit-scrollbar-thumb {
            border-radius: 10px;
            height: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
            box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
            background-color: #555;
        }
        
        body::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
            box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
            border-radius: 10px;
            background-color: #F5F5F5;
        }
```

**Comment by xgqfrms-gildata** [comment]
https://github.com/gildata/RAIO/issues/40

https://github.com/gildata/RAIO/issues/108

**Comment by xgqfrms-gildata** [comment]
```css

.h5-dnd-icon-container {
    /* border: 1px solid #777; */
    box-sizing: border-box;
    /* absolute center */
    width: 280px;
    /* 270 + 10 */
    min-height: 250px;
    height: 100vh;
    background: #ccc;
    overflow-y: scroll;
}


/* scrollbar width 10*/

.h5-dnd-icon-container::-webkit-scrollbar {
    width: 8px;
    /* scrollbar width */
}

.h5-dnd-icon-container::-webkit-scrollbar-thumb {
    border-radius: 10px;
    height: 10px;
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
    background-color: #555;
}

.h5-dnd-icon-container::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    border-radius: 10px;
    background-color: #F5F5F5;
}


```
