### ISSUE TITLE
ES2017 Async + Await 

### ISSUE THREAD

**Issue by xgqfrms-gildata** [gildata/RAIO#81]
# ES2017 Async + Await 

https://learnnode.com/

![image](https://user-images.githubusercontent.com/29531779/29394543-936e1efe-833d-11e7-86cd-ddb5fe1bc477.png)

```js


const editStore = async (req="default value", res="") => {
    const {id} = req.params;
    const store = await Store.findeById(id);
    await confirmOwner(store, req.user);
    res.render(`editStore`, {store});
};


/*

async await

const

destructuring assignment

arrow function

default value

// ??? generator yeild 


*/

```

# css ` border-radius: 50%;` & `transform: rotate(-45deg);`

> circle & line

```css

.foo-bar .crossouts .crossout {
    margin: 0 2rem;
    font-size: 5rem;
    text-indent: -1.5rem;
    font-family: 'radnika-bold';
    border: 5px solid #c528ef;
    line-height: 70px;
    width: 80px;
    box-shadow: 0 0 5px rgba(0,0,0,0.2);
    text-align: center;
    border-radius: 50%;
    border-top-left-radius: 50%;
    border-top-right-radius: 50%;
    border-bottom-right-radius: 50%;
    border-bottom-left-radius: 50%;
    position: relative;
}


.foo-bar .crossouts .crossout:before {
    display: block;
    content: '';
    position: absolute;
    width: 130%;
    height: 5px;
    background: #28ef5d;
    top: 50%;
    left: -10%;
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
}

```

![image](https://user-images.githubusercontent.com/29531779/29394754-025247f4-833f-11e7-8b25-59f59d2b2380.png)
